# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.agent_run_event import AgentRunEvent
from ..types.agent_run_response import AgentRunResponse
from .raw_client import AsyncRawAgentClient, RawAgentClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AgentClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAgentClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAgentClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAgentClient
        """
        return self._raw_client

    def run_stream(
        self,
        *,
        prompt: str,
        model: typing.Optional[str] = OMIT,
        chat_id: typing.Optional[str] = OMIT,
        save: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Iterator[AgentRunEvent]:
        """
        Run the Labric data-analysis agent and return its final answer
        alongside the tool calls it made. With stream=true the response is
        instead a stream of server-sent AgentRunEvent events, closing after a
        terminal `result` event that carries the same summary, or an `error`
        event if the run fails; prefer streaming for long analyses. Pass chat_id
        to continue a saved conversation, or save=true to save the run as a new
        chat visible in the web UI; if saving fails, the answer is still returned
        but its chat_id is null.

        Parameters
        ----------
        prompt : str

        model : typing.Optional[str]

        chat_id : typing.Optional[str]

        save : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.Iterator[AgentRunEvent]


        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        response = client.agent.run_stream(
            prompt="prompt",
        )
        for chunk in response:
            yield chunk
        """
        with self._raw_client.run_stream(
            prompt=prompt, model=model, chat_id=chat_id, save=save, request_options=request_options
        ) as r:
            yield from r.data

    def run(
        self,
        *,
        prompt: str,
        model: typing.Optional[str] = OMIT,
        chat_id: typing.Optional[str] = OMIT,
        save: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentRunResponse:
        """
        Run the Labric data-analysis agent and return its final answer
        alongside the tool calls it made. With stream=true the response is
        instead a stream of server-sent AgentRunEvent events, closing after a
        terminal `result` event that carries the same summary, or an `error`
        event if the run fails; prefer streaming for long analyses. Pass chat_id
        to continue a saved conversation, or save=true to save the run as a new
        chat visible in the web UI; if saving fails, the answer is still returned
        but its chat_id is null.

        Parameters
        ----------
        prompt : str

        model : typing.Optional[str]

        chat_id : typing.Optional[str]

        save : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentRunResponse


        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.agent.run(
            prompt="prompt",
        )
        """
        _response = self._raw_client.run(
            prompt=prompt, model=model, chat_id=chat_id, save=save, request_options=request_options
        )
        return _response.data


class AsyncAgentClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAgentClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAgentClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAgentClient
        """
        return self._raw_client

    async def run_stream(
        self,
        *,
        prompt: str,
        model: typing.Optional[str] = OMIT,
        chat_id: typing.Optional[str] = OMIT,
        save: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.AsyncIterator[AgentRunEvent]:
        """
        Run the Labric data-analysis agent and return its final answer
        alongside the tool calls it made. With stream=true the response is
        instead a stream of server-sent AgentRunEvent events, closing after a
        terminal `result` event that carries the same summary, or an `error`
        event if the run fails; prefer streaming for long analyses. Pass chat_id
        to continue a saved conversation, or save=true to save the run as a new
        chat visible in the web UI; if saving fails, the answer is still returned
        but its chat_id is null.

        Parameters
        ----------
        prompt : str

        model : typing.Optional[str]

        chat_id : typing.Optional[str]

        save : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.AsyncIterator[AgentRunEvent]


        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.agent.run_stream(
                prompt="prompt",
            )
            async for chunk in response:
                yield chunk


        asyncio.run(main())
        """
        async with self._raw_client.run_stream(
            prompt=prompt, model=model, chat_id=chat_id, save=save, request_options=request_options
        ) as r:
            async for _chunk in r.data:
                yield _chunk

    async def run(
        self,
        *,
        prompt: str,
        model: typing.Optional[str] = OMIT,
        chat_id: typing.Optional[str] = OMIT,
        save: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentRunResponse:
        """
        Run the Labric data-analysis agent and return its final answer
        alongside the tool calls it made. With stream=true the response is
        instead a stream of server-sent AgentRunEvent events, closing after a
        terminal `result` event that carries the same summary, or an `error`
        event if the run fails; prefer streaming for long analyses. Pass chat_id
        to continue a saved conversation, or save=true to save the run as a new
        chat visible in the web UI; if saving fails, the answer is still returned
        but its chat_id is null.

        Parameters
        ----------
        prompt : str

        model : typing.Optional[str]

        chat_id : typing.Optional[str]

        save : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentRunResponse


        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent.run(
                prompt="prompt",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.run(
            prompt=prompt, model=model, chat_id=chat_id, save=save, request_options=request_options
        )
        return _response.data
