# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_run_response import AgentRunResponse


class AgentRunEvent(UniversalBaseModel):
    """
    One streamed agent run event, discriminated by `type`:

    - `text_delta` / `reasoning_delta`: incremental assistant text in `delta`
    - `tool_call`: the agent invoked a tool (`tool_call_id`, `tool_name`, `input`)
    - `tool_result`: a tool finished (`tool_call_id`, `tool_name`, `output`)
    - `result`: terminal event carrying the full run summary in `result`
    - `error`: the run or its persistence failed; details in `error`
    """

    type: str
    delta: typing.Optional[str] = None
    tool_call_id: typing.Optional[str] = None
    tool_name: typing.Optional[str] = None
    input: typing.Optional[typing.Any] = None
    output: typing.Optional[typing.Any] = None
    result: typing.Optional[AgentRunResponse] = None
    error: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
