# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_run_usage import AgentRunUsage
from .agent_tool_call import AgentToolCall


class AgentRunResponse(UniversalBaseModel):
    """
    Final result of an agent run: the assistant's answer, the tool calls it
    made, token usage, and the chat id when the run was persisted.
    """

    output: str
    model: str
    tool_calls: typing.List[AgentToolCall]
    usage: AgentRunUsage
    chat_id: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
