# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .batch_write_options_mode import BatchWriteOptionsMode


class BatchWriteOptions(UniversalBaseModel):
    """
    Options for controlling batch write behavior.
    """

    mode: typing.Optional[BatchWriteOptionsMode] = pydantic.Field(default=None)
    """
    'insert' creates new records, and fails if the record already exists. 'upsert' creates or updates based on match_on columns.
    """

    match_on: typing.Optional[typing.Dict[str, typing.Optional[typing.List[str]]]] = pydantic.Field(default=None)
    """
    For upsert: which columns to match on, per table. Example: {"production_run": ["run_code"]}
    """

    dry_run: typing.Optional[bool] = pydantic.Field(default=None)
    """
    If True, validate without committing changes.
    """

    return_records: typing.Optional[bool] = pydantic.Field(default=None)
    """
    If True, include created/updated records in response.
    """

    job_execution_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Existing job execution to attach this write to. If omitted, a new one is created and returned, so the write can be reverted as a unit.
    """

    job_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name for the auto-created job. Defaults to 'Off-Platform Manual Job'.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
