# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .table_summary import TableSummary
from .write_plan import WritePlan


class BatchWriteResponse(UniversalBaseModel):
    """
    Response from a successful batch write.
    """

    success: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the operation succeeded.
    """

    job_execution_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The job execution this write was recorded under. Use it to revert the write as a unit. Null for dry runs.
    """

    summary: typing.Dict[str, TableSummary] = pydantic.Field()
    """
    Count of created/updated records per table.
    """

    refs: typing.Dict[str, str] = pydantic.Field()
    """
    Map of _ref labels to their created IDs.
    """

    records: typing.Optional[typing.Dict[str, typing.Optional[typing.List[typing.Dict[str, typing.Any]]]]] = (
        pydantic.Field(default=None)
    )
    """
    Created/updated records (only if return_records=True).
    """

    plan: typing.Optional[WritePlan] = pydantic.Field(default=None)
    """
    Execution plan (only if dry_run=True).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
