# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class FileContentSchema(UniversalBaseModel):
    """
    The content of a source data file, for inspecting raw instrument output.
    """

    file_id: str
    file_name: typing.Optional[str] = None
    size_kilobytes: typing.Optional[int] = None
    download_url: str = pydantic.Field()
    """
    Presigned URL to fetch the full file (e.g. via the SDK).
    """

    text_preview: typing.Optional[str] = pydantic.Field(default=None)
    """
    Best-effort UTF-8 decode of the start of the file, or null if skipped.
    """

    preview_truncated: bool = pydantic.Field()
    """
    True if the file is longer than the inlined preview.
    """

    preview_skipped_reason: typing.Optional[str] = pydantic.Field(default=None)
    """
    Why an inline preview was not returned (e.g. file too large).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
