# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class FileUploadUrlSchema(UniversalBaseModel):
    file_id: str = pydantic.Field()
    """
    The ID of the file record awaiting its bytes.
    """

    upload_url: str = pydantic.Field()
    """
    Signed Google Cloud Storage URL. Send the file bytes as the body of an HTTP PUT to this URL with no Authorization header.
    """

    headers: typing.Dict[str, str] = pydantic.Field()
    """
    Headers the PUT must carry exactly as given; the URL is signed for them. They set the Content-Type, let the object be created but not replaced, and cap the body at the platform's file size limit.
    """

    expires_at: str = pydantic.Field()
    """
    When the upload URL stops working, as an ISO 8601 timestamp.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
