# This file was auto-generated by Fern from our API Definition.

import typing

MlProblemType = typing.Union[typing.Literal["binary", "multiclass", "regression", "semantic_segmentation"], typing.Any]
