# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class OffPlatformJobExecutionSchema(UniversalBaseModel):
    """
    A job execution to attribute off-platform writes and uploads to.
    """

    job_execution_id: str = pydantic.Field()
    """
    Pass this as job_execution_id to the write and upload-file tools.
    """

    job_id: str = pydantic.Field()
    """
    ID of the job the execution belongs to.
    """

    job_name: str = pydantic.Field()
    """
    Name of the job the execution belongs to.
    """

    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    The execution's current status.
    """

    started_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the execution started.
    """

    completed_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the execution ended, or null while it is still running.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
