# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PredictedAnnotationSchema(UniversalBaseModel):
    """
    A predicted mask shaped as an annotation payload, tied back to the
    input row's image file. Nothing is persisted by predict: to store it,
    pass label/mask/width/height to POST /images/{file_id}/annotations with
    is_autogenerated=true.
    """

    file_id: str
    label: str
    mask: str
    width: int
    height: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
