# This file was auto-generated by Fern from our API Definition.

import typing

QualityPreset = typing.Union[
    typing.Literal["best_quality", "high_quality", "good_quality", "medium_quality"], typing.Any
]
