# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .queryable_column_schema import QueryableColumnSchema


class QueryableTableSchema(UniversalBaseModel):
    """
    A table SQL queries can target. Platform tables have no id.
    """

    id: typing.Optional[int] = None
    name: str
    description: typing.Optional[str] = None
    semantic_category: typing.Optional[str] = None
    columns: typing.List[QueryableColumnSchema]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
