# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class QueryableColumnSchema(UniversalBaseModel):
    """
    A column of a queryable table. Platform table columns have no id.
    """

    id: typing.Optional[int] = None
    name: str
    sql_column_name: str
    description: typing.Optional[str] = None
    data_type: str
    is_primary_key: bool
    is_foreign_key: bool
    is_nullable: bool
    is_unique: bool
    foreign_key_table_name: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
