# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SaveAnnotationSchema(UniversalBaseModel):
    """
    A new mask for a label on an image: the update payload plus the
    identity fields an existing row already has.
    """

    mask: str
    width: typing.Optional[int] = None
    height: typing.Optional[int] = None
    label: str
    is_human_vetted: typing.Optional[bool] = None
    file_id: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
