# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .series_write_parent import SeriesWriteParent


class SeriesWrite(UniversalBaseModel):
    """
    A raw data series belonging to one parent row, given column by column.
    """

    table: str = pydantic.Field()
    """
    Raw table that holds the series.
    """

    parent: SeriesWriteParent = pydantic.Field()
    """
    Parent row that owns the series: an id, an '@<label>' reference to a row written in this request, or a lookup object such as {'name': 'M-001'}.
    """

    parent_column: typing.Optional[str] = pydantic.Field(default=None)
    """
    Foreign key column that points at the parent. Required only when the raw table has more than one foreign key.
    """

    columns: typing.Dict[str, typing.List[typing.Any]] = pydantic.Field()
    """
    Values keyed by column name. Every list holds one value per point and all lists have the same length. An integer 'order' column is filled with each point's position unless given here.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
