# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .table_write_mode import TableWriteMode
from .table_write_on_match import TableWriteOnMatch


class TableWrite(UniversalBaseModel):
    """
    Rows to write to one table.
    """

    table: str = pydantic.Field()
    """
    Table to write to: one of the organization's tables, or a core table such as experiment, operation, or carrier.
    """

    rows: typing.List[typing.Dict[str, typing.Any]] = pydantic.Field()
    """
    Rows keyed by column name. A row may carry '_ref': '<label>' so later rows and series can point at it with '@<label>'. A foreign key value may be an id, an '@<label>' reference to an earlier row, or a lookup object such as {'name': 'S-001'} that matches exactly one row that existed before the request. Omit a string 'id' primary key to have it generated.
    """

    mode: typing.Optional[TableWriteMode] = pydantic.Field(default=None)
    """
    'insert' creates every row. 'upsert' updates rows that match on key and creates the rest. 'update' and 'delete' require every row to match on key.
    """

    key: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Columns that identify an existing row for upsert, update, and delete. Defaults to the primary key.
    """

    cascade: typing.Optional[bool] = pydantic.Field(default=None)
    """
    For delete: also delete rows of other tables that reference the deleted rows. Rows of raw tables are always deleted with the row they belong to. Without cascade, a delete that other rows reference is rejected.
    """

    on_match: typing.Optional[TableWriteOnMatch] = pydantic.Field(default=None)
    """
    How a matched row takes the provided columns. 'overwrite' replaces them. 'fill_missing' only sets columns that are currently null. Columns absent from the row are never changed.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
