# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ToolsFileInfoSchema(UniversalBaseModel):
    """
    A source data file available for parser development.
    """

    file_id: str = pydantic.Field()
    """
    The file's ID, for use with the file-content tool.
    """

    original_path: typing.Optional[str] = pydantic.Field(default=None)
    """
    Original file name / path.
    """

    source_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Where the file came from (e.g. instrument sync, manual upload).
    """

    source_instrument_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of the instrument that produced the file, if any.
    """

    size_kilobytes: typing.Optional[int] = pydantic.Field(default=None)
    """
    File size in kilobytes.
    """

    crc32c_hash: typing.Optional[str] = pydantic.Field(default=None)
    """
    Content hash, useful as an idempotency key for parsed rows.
    """

    file_created_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the source file was created, if known.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
