# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ToolsMlModelSchema(UniversalBaseModel):
    """
    Flat model summary for the SDK/MCP tools surface: everything a caller
    needs to pick a model and build a predict payload, without nested versions.
    """

    id: str
    name: str
    description: typing.Optional[str] = None
    task_type: str
    status: typing.Optional[str] = None
    target_column: typing.Optional[str] = None
    feature_columns: typing.Optional[typing.List[str]] = None
    image_columns: typing.Optional[typing.List[str]] = None
    problem_type: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
