# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ToolsJobSchema(UniversalBaseModel):
    """
    A job that runs a script on the platform.
    """

    id: str = pydantic.Field()
    """
    Pass this as job_id to the job execution tools.
    """

    name: str
    description: typing.Optional[str] = None
    archived: bool

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
