# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ToolsMlModelDetailSchema(UniversalBaseModel):
    """
    ToolsMLModelSchema plus the active version's training state, so a
    caller that started a training run can poll one flat object for progress,
    failure detail, and final metrics.
    """

    id: str
    name: str
    description: typing.Optional[str] = None
    task_type: str
    status: typing.Optional[str] = None
    target_column: typing.Optional[str] = None
    feature_columns: typing.Optional[typing.List[str]] = None
    image_columns: typing.Optional[typing.List[str]] = None
    problem_type: typing.Optional[str] = None
    version_number: typing.Optional[int] = None
    dataset_id: typing.Optional[str] = None
    quality_preset: typing.Optional[str] = None
    error_message: typing.Optional[str] = None
    training_started_at: typing.Optional[dt.datetime] = None
    training_completed_at: typing.Optional[dt.datetime] = None
    evaluation_metrics: typing.Optional[typing.Dict[str, typing.Any]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
