# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class WriteDataProblem(UniversalBaseModel):
    path: typing.Optional[str] = pydantic.Field(default=None)
    """
    Place in the request the problem concerns, such as tables[1].rows[0].sample or series[0].columns.value. Null when it concerns the request as a whole, such as a table constraint violation.
    """

    message: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
