# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .write_data_problem import WriteDataProblem


class WriteDataErrorResponse(UniversalBaseModel):
    errors: typing.List[WriteDataProblem] = pydantic.Field()
    """
    Problems with the request. Past 100, a final problem counts the ones left out.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
