# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class WritePlan(UniversalBaseModel):
    """
    Execution plan returned by dry_run.
    """

    insert_order: typing.List[str] = pydantic.Field()
    """
    Order in which tables will be inserted.
    """

    operations: typing.List[typing.Dict[str, typing.Any]] = pydantic.Field()
    """
    Operations that would be performed.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
