# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.annotation_schema import AnnotationSchema
from ..types.save_annotation_schema import SaveAnnotationSchema
from .raw_client import AsyncRawImagesClient, RawImagesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ImagesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawImagesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawImagesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawImagesClient
        """
        return self._raw_client

    def annotate(
        self,
        file_id: str,
        *,
        annotations: typing.Sequence[SaveAnnotationSchema],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[AnnotationSchema]:
        """
        Save masks on an image as annotations, one per entry.

        Each entry is a binary mask PNG (white-on-transparent, base64-encoded)
        for a label; labels are created on first use. Saving is additive, so
        a label can accumulate several masks on the same image. The annotations
        a segmentation model returns from predict can be passed straight through;
        each names the file it was predicted for, and one for a different file
        rejects the request. Leave is_human_vetted false for automated saves:
        the mask editor flags unvetted masks for review, and only vetted masks
        feed training. The file must be a processed image. All-or-nothing: one
        bad entry rejects the whole request.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        file_id : str

        annotations : typing.Sequence[SaveAnnotationSchema]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[AnnotationSchema]
            OK

        Examples
        --------
        from labric import Labric, SaveAnnotationSchema

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.images.annotate(
            file_id="file_id",
            annotations=[
                SaveAnnotationSchema(
                    mask="mask",
                    label="label",
                )
            ],
        )
        """
        _response = self._raw_client.annotate(file_id, annotations=annotations, request_options=request_options)
        return _response.data


class AsyncImagesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawImagesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawImagesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawImagesClient
        """
        return self._raw_client

    async def annotate(
        self,
        file_id: str,
        *,
        annotations: typing.Sequence[SaveAnnotationSchema],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[AnnotationSchema]:
        """
        Save masks on an image as annotations, one per entry.

        Each entry is a binary mask PNG (white-on-transparent, base64-encoded)
        for a label; labels are created on first use. Saving is additive, so
        a label can accumulate several masks on the same image. The annotations
        a segmentation model returns from predict can be passed straight through;
        each names the file it was predicted for, and one for a different file
        rejects the request. Leave is_human_vetted false for automated saves:
        the mask editor flags unvetted masks for review, and only vetted masks
        feed training. The file must be a processed image. All-or-nothing: one
        bad entry rejects the whole request.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        file_id : str

        annotations : typing.Sequence[SaveAnnotationSchema]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[AnnotationSchema]
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric, SaveAnnotationSchema

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.images.annotate(
                file_id="file_id",
                annotations=[
                    SaveAnnotationSchema(
                        mask="mask",
                        label="label",
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.annotate(file_id, annotations=annotations, request_options=request_options)
        return _response.data
