# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .bad_gateway_error import BadGatewayError
    from .bad_request_error import BadRequestError
    from .conflict_error import ConflictError
    from .forbidden_error import ForbiddenError
    from .gateway_timeout_error import GatewayTimeoutError
    from .gone_error import GoneError
    from .im_a_teapot_error import ImATeapotError
    from .internal_server_error import InternalServerError
    from .length_required_error import LengthRequiredError
    from .method_not_allowed_error import MethodNotAllowedError
    from .not_acceptable_error import NotAcceptableError
    from .not_found_error import NotFoundError
    from .not_implemented_error import NotImplementedError
    from .payment_required_error import PaymentRequiredError
    from .precondition_failed_error import PreconditionFailedError
    from .proxy_authentication_required_error import ProxyAuthenticationRequiredError
    from .range_not_satisfiable_error import RangeNotSatisfiableError
    from .request_timeout_error import RequestTimeoutError
    from .service_unavailable_error import ServiceUnavailableError
    from .too_early_error import TooEarlyError
    from .too_many_requests_error import TooManyRequestsError
    from .unauthorized_error import UnauthorizedError
    from .unavailable_for_legal_reasons_error import UnavailableForLegalReasonsError
_dynamic_imports: typing.Dict[str, str] = {
    "BadGatewayError": ".bad_gateway_error",
    "BadRequestError": ".bad_request_error",
    "ConflictError": ".conflict_error",
    "ForbiddenError": ".forbidden_error",
    "GatewayTimeoutError": ".gateway_timeout_error",
    "GoneError": ".gone_error",
    "ImATeapotError": ".im_a_teapot_error",
    "InternalServerError": ".internal_server_error",
    "LengthRequiredError": ".length_required_error",
    "MethodNotAllowedError": ".method_not_allowed_error",
    "NotAcceptableError": ".not_acceptable_error",
    "NotFoundError": ".not_found_error",
    "NotImplementedError": ".not_implemented_error",
    "PaymentRequiredError": ".payment_required_error",
    "PreconditionFailedError": ".precondition_failed_error",
    "ProxyAuthenticationRequiredError": ".proxy_authentication_required_error",
    "RangeNotSatisfiableError": ".range_not_satisfiable_error",
    "RequestTimeoutError": ".request_timeout_error",
    "ServiceUnavailableError": ".service_unavailable_error",
    "TooEarlyError": ".too_early_error",
    "TooManyRequestsError": ".too_many_requests_error",
    "UnauthorizedError": ".unauthorized_error",
    "UnavailableForLegalReasonsError": ".unavailable_for_legal_reasons_error",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "BadGatewayError",
    "BadRequestError",
    "ConflictError",
    "ForbiddenError",
    "GatewayTimeoutError",
    "GoneError",
    "ImATeapotError",
    "InternalServerError",
    "LengthRequiredError",
    "MethodNotAllowedError",
    "NotAcceptableError",
    "NotFoundError",
    "NotImplementedError",
    "PaymentRequiredError",
    "PreconditionFailedError",
    "ProxyAuthenticationRequiredError",
    "RangeNotSatisfiableError",
    "RequestTimeoutError",
    "ServiceUnavailableError",
    "TooEarlyError",
    "TooManyRequestsError",
    "UnauthorizedError",
    "UnavailableForLegalReasonsError",
]
