# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.api_error import ApiError
from ..types.error_schema import ErrorSchema


class PreconditionFailedError(ApiError):
    def __init__(self, body: ErrorSchema, headers: typing.Optional[typing.Dict[str, str]] = None):
        super().__init__(status_code=412, headers=headers, body=body)
