# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.api_error import ApiError
from ..types.validation_error_schema import ValidationErrorSchema


class UnprocessableEntityError(ApiError):
    def __init__(self, body: ValidationErrorSchema, headers: typing.Optional[typing.Dict[str, str]] = None):
        super().__init__(status_code=422, headers=headers, body=body)
