# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.off_platform_job_execution_schema import OffPlatformJobExecutionSchema
from ..types.revert_result_schema import RevertResultSchema
from ..types.start_job_execution_schema import StartJobExecutionSchema
from .raw_client import AsyncRawJobsClient, RawJobsClient
from .types.update_job_execution_status_schema_status import UpdateJobExecutionStatusSchemaStatus

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class JobsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawJobsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawJobsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawJobsClient
        """
        return self._raw_client

    def start(
        self,
        *,
        request: typing.Optional[StartJobExecutionSchema] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OffPlatformJobExecutionSchema:
        """
        Open a job execution for a script running outside the platform.

        Pass the returned job_execution_id to the write and upload-file tools so
        everything one script run produces is attributed to a single execution and
        can be inspected or reverted as a unit. Pass job_id to run under an
        existing job, job_name to run under a job of that name (created if
        missing), or neither to run under the default off-platform job.

        The execution is marked running immediately. Close it as completed or
        failed when the script finishes. Pass timeout_minutes to have the platform
        fail it after that long if the script has not closed it, so a crashed
        script does not leave it running forever.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        request : typing.Optional[StartJobExecutionSchema]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OffPlatformJobExecutionSchema
            OK

        Examples
        --------
        from labric import Labric, StartJobExecutionSchema

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.jobs.start(
            request=StartJobExecutionSchema(),
        )
        """
        _response = self._raw_client.start(request=request, request_options=request_options)
        return _response.data

    def close(
        self,
        execution_id: str,
        *,
        status: UpdateJobExecutionStatusSchemaStatus,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OffPlatformJobExecutionSchema:
        """
        Close a job execution as completed or failed.

        Call this when an off-platform script finishes. Either status is final:
        re-sending the same status is a no-op, and changing it is rejected. Only
        executions opened by the start tool are accepted; the platform records
        every other execution's status itself.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        execution_id : str

        status : UpdateJobExecutionStatusSchemaStatus
            How the run ended. Either status is final: the execution cannot change status afterwards.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OffPlatformJobExecutionSchema
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.jobs.close(
            execution_id="execution_id",
            status="completed",
        )
        """
        _response = self._raw_client.close(execution_id, status=status, request_options=request_options)
        return _response.data

    def revert(
        self, execution_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RevertResultSchema:
        """
        Revert a job execution by deleting the rows it created.

        Deletes the execution's created objects and their linked raw rows in one
        transaction, for undoing a test write that failed validation. Updates and
        deletes cannot be reversed and are reported as warnings in the result.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        execution_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RevertResultSchema
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.jobs.revert(
            execution_id="execution_id",
        )
        """
        _response = self._raw_client.revert(execution_id, request_options=request_options)
        return _response.data


class AsyncJobsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawJobsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawJobsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawJobsClient
        """
        return self._raw_client

    async def start(
        self,
        *,
        request: typing.Optional[StartJobExecutionSchema] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OffPlatformJobExecutionSchema:
        """
        Open a job execution for a script running outside the platform.

        Pass the returned job_execution_id to the write and upload-file tools so
        everything one script run produces is attributed to a single execution and
        can be inspected or reverted as a unit. Pass job_id to run under an
        existing job, job_name to run under a job of that name (created if
        missing), or neither to run under the default off-platform job.

        The execution is marked running immediately. Close it as completed or
        failed when the script finishes. Pass timeout_minutes to have the platform
        fail it after that long if the script has not closed it, so a crashed
        script does not leave it running forever.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        request : typing.Optional[StartJobExecutionSchema]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OffPlatformJobExecutionSchema
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric, StartJobExecutionSchema

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.jobs.start(
                request=StartJobExecutionSchema(),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.start(request=request, request_options=request_options)
        return _response.data

    async def close(
        self,
        execution_id: str,
        *,
        status: UpdateJobExecutionStatusSchemaStatus,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OffPlatformJobExecutionSchema:
        """
        Close a job execution as completed or failed.

        Call this when an off-platform script finishes. Either status is final:
        re-sending the same status is a no-op, and changing it is rejected. Only
        executions opened by the start tool are accepted; the platform records
        every other execution's status itself.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        execution_id : str

        status : UpdateJobExecutionStatusSchemaStatus
            How the run ended. Either status is final: the execution cannot change status afterwards.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OffPlatformJobExecutionSchema
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.jobs.close(
                execution_id="execution_id",
                status="completed",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.close(execution_id, status=status, request_options=request_options)
        return _response.data

    async def revert(
        self, execution_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RevertResultSchema:
        """
        Revert a job execution by deleting the rows it created.

        Deletes the execution's created objects and their linked raw rows in one
        transaction, for undoing a test write that failed validation. Updates and
        deletes cannot be reversed and are reported as warnings in the result.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        execution_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RevertResultSchema
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.jobs.revert(
                execution_id="execution_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.revert(execution_id, request_options=request_options)
        return _response.data
