# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_request_error import BadRequestError
from ..errors.forbidden_error import ForbiddenError
from ..errors.internal_server_error import InternalServerError
from ..errors.not_found_error import NotFoundError
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.error_schema import ErrorSchema
from ..types.off_platform_job_execution_schema import OffPlatformJobExecutionSchema
from ..types.revert_result_schema import RevertResultSchema
from ..types.start_job_execution_schema import StartJobExecutionSchema
from ..types.validation_error_schema import ValidationErrorSchema
from .types.update_job_execution_status_schema_status import UpdateJobExecutionStatusSchemaStatus
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawJobsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def start(
        self,
        *,
        request: typing.Optional[StartJobExecutionSchema] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[OffPlatformJobExecutionSchema]:
        """
        Open a job execution for a script running outside the platform.

        Pass the returned job_execution_id to the write and upload-file tools so
        everything one script run produces is attributed to a single execution and
        can be inspected or reverted as a unit. Pass job_id to run under an
        existing job, job_name to run under a job of that name (created if
        missing), or neither to run under the default off-platform job.

        The execution is marked running immediately. Close it as completed or
        failed when the script finishes. Pass timeout_minutes to have the platform
        fail it after that long if the script has not closed it, so a crashed
        script does not leave it running forever.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        request : typing.Optional[StartJobExecutionSchema]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[OffPlatformJobExecutionSchema]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/job-executions",
            method="POST",
            json=convert_and_respect_annotation_metadata(
                object_=request, annotation=typing.Optional[StartJobExecutionSchema], direction="write"
            ),
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OffPlatformJobExecutionSchema,
                    parse_obj_as(
                        type_=OffPlatformJobExecutionSchema,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorSchema,
                        parse_obj_as(
                            type_=ValidationErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def close(
        self,
        execution_id: str,
        *,
        status: UpdateJobExecutionStatusSchemaStatus,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[OffPlatformJobExecutionSchema]:
        """
        Close a job execution as completed or failed.

        Call this when an off-platform script finishes. Either status is final:
        re-sending the same status is a no-op, and changing it is rejected. Only
        executions opened by the start tool are accepted; the platform records
        every other execution's status itself.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        execution_id : str

        status : UpdateJobExecutionStatusSchemaStatus
            How the run ended. Either status is final: the execution cannot change status afterwards.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[OffPlatformJobExecutionSchema]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/job-executions/{encode_path_param(execution_id)}",
            method="PATCH",
            json={
                "status": status,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OffPlatformJobExecutionSchema,
                    parse_obj_as(
                        type_=OffPlatformJobExecutionSchema,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorSchema,
                        parse_obj_as(
                            type_=ValidationErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def revert(
        self, execution_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[RevertResultSchema]:
        """
        Revert a job execution by deleting the rows it created.

        Deletes the execution's created objects and their linked raw rows in one
        transaction, for undoing a test write that failed validation. Updates and
        deletes cannot be reversed and are reported as warnings in the result.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        execution_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[RevertResultSchema]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/job-executions/{encode_path_param(execution_id)}/revert",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RevertResultSchema,
                    parse_obj_as(
                        type_=RevertResultSchema,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorSchema,
                        parse_obj_as(
                            type_=ValidationErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawJobsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def start(
        self,
        *,
        request: typing.Optional[StartJobExecutionSchema] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[OffPlatformJobExecutionSchema]:
        """
        Open a job execution for a script running outside the platform.

        Pass the returned job_execution_id to the write and upload-file tools so
        everything one script run produces is attributed to a single execution and
        can be inspected or reverted as a unit. Pass job_id to run under an
        existing job, job_name to run under a job of that name (created if
        missing), or neither to run under the default off-platform job.

        The execution is marked running immediately. Close it as completed or
        failed when the script finishes. Pass timeout_minutes to have the platform
        fail it after that long if the script has not closed it, so a crashed
        script does not leave it running forever.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        request : typing.Optional[StartJobExecutionSchema]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[OffPlatformJobExecutionSchema]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/job-executions",
            method="POST",
            json=convert_and_respect_annotation_metadata(
                object_=request, annotation=typing.Optional[StartJobExecutionSchema], direction="write"
            ),
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OffPlatformJobExecutionSchema,
                    parse_obj_as(
                        type_=OffPlatformJobExecutionSchema,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorSchema,
                        parse_obj_as(
                            type_=ValidationErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def close(
        self,
        execution_id: str,
        *,
        status: UpdateJobExecutionStatusSchemaStatus,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[OffPlatformJobExecutionSchema]:
        """
        Close a job execution as completed or failed.

        Call this when an off-platform script finishes. Either status is final:
        re-sending the same status is a no-op, and changing it is rejected. Only
        executions opened by the start tool are accepted; the platform records
        every other execution's status itself.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        execution_id : str

        status : UpdateJobExecutionStatusSchemaStatus
            How the run ended. Either status is final: the execution cannot change status afterwards.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[OffPlatformJobExecutionSchema]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/job-executions/{encode_path_param(execution_id)}",
            method="PATCH",
            json={
                "status": status,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OffPlatformJobExecutionSchema,
                    parse_obj_as(
                        type_=OffPlatformJobExecutionSchema,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorSchema,
                        parse_obj_as(
                            type_=ValidationErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def revert(
        self, execution_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[RevertResultSchema]:
        """
        Revert a job execution by deleting the rows it created.

        Deletes the execution's created objects and their linked raw rows in one
        transaction, for undoing a test write that failed validation. Updates and
        deletes cannot be reversed and are reported as warnings in the result.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        execution_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[RevertResultSchema]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/job-executions/{encode_path_param(execution_id)}/revert",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RevertResultSchema,
                    parse_obj_as(
                        type_=RevertResultSchema,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorSchema,
                        parse_obj_as(
                            type_=ValidationErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
