# This file was auto-generated by Fern from our API Definition.

import typing

from .. import core
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.file_content_schema import FileContentSchema
from ..types.file_info_schema import FileInfoSchema
from ..types.file_upload_schema import FileUploadSchema
from .raw_client import AsyncRawFilesClient, RawFilesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class FilesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFilesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawFilesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFilesClient
        """
        return self._raw_client

    def list(
        self,
        *,
        instrument_id: typing.Optional[str] = None,
        extensions: typing.Optional[str] = None,
        query: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[FileInfoSchema]:
        """
        List source data files available for parser development.

        Returns a representative set of uploaded files for the org, newest first.
        Filter by instrument_id, comma-separated file extensions (e.g. "csv,txt"),
        or a substring of the file name. Use the file-content tool to inspect a
        file's raw contents.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        instrument_id : typing.Optional[str]

        extensions : typing.Optional[str]

        query : typing.Optional[str]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[FileInfoSchema]
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.files.list()
        """
        _response = self._raw_client.list(
            instrument_id=instrument_id,
            extensions=extensions,
            query=query,
            limit=limit,
            request_options=request_options,
        )
        return _response.data

    def upload(
        self,
        *,
        file: core.File,
        job_execution_id: typing.Optional[str] = OMIT,
        instrument_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FileUploadSchema:
        """
        Upload a file.

        Accepts a multipart/form-data file upload, stores it in GCS, and returns the
        created file record. At least one of job_execution_id and instrument_id is
        required: pass a job_execution_id for an artifact of a job running in a
        sandbox, which also records provenance linking the file to that execution,
        and pass an instrument_id for data captured off-platform by an instrument the
        Sync app cannot reach, which attaches the file to that instrument so
        instrument triggers and parsers pick it up.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        file : core.File
            See core.File for more documentation

        job_execution_id : typing.Optional[str]

        instrument_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileUploadSchema
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.files.upload()
        """
        _response = self._raw_client.upload(
            file=file, job_execution_id=job_execution_id, instrument_id=instrument_id, request_options=request_options
        )
        return _response.data

    def get_content(
        self, file_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> FileContentSchema:
        """
        Fetch a source file's content for inspecting raw instrument output.

        Returns a presigned download URL plus a best-effort UTF-8 text preview of
        the start of the file. Large files return a URL only (no inline preview);
        fetch the full bytes via the URL when needed.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        file_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileContentSchema
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.files.get_content(
            file_id="file_id",
        )
        """
        _response = self._raw_client.get_content(file_id, request_options=request_options)
        return _response.data


class AsyncFilesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFilesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawFilesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFilesClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        instrument_id: typing.Optional[str] = None,
        extensions: typing.Optional[str] = None,
        query: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[FileInfoSchema]:
        """
        List source data files available for parser development.

        Returns a representative set of uploaded files for the org, newest first.
        Filter by instrument_id, comma-separated file extensions (e.g. "csv,txt"),
        or a substring of the file name. Use the file-content tool to inspect a
        file's raw contents.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        instrument_id : typing.Optional[str]

        extensions : typing.Optional[str]

        query : typing.Optional[str]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[FileInfoSchema]
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.files.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            instrument_id=instrument_id,
            extensions=extensions,
            query=query,
            limit=limit,
            request_options=request_options,
        )
        return _response.data

    async def upload(
        self,
        *,
        file: core.File,
        job_execution_id: typing.Optional[str] = OMIT,
        instrument_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FileUploadSchema:
        """
        Upload a file.

        Accepts a multipart/form-data file upload, stores it in GCS, and returns the
        created file record. At least one of job_execution_id and instrument_id is
        required: pass a job_execution_id for an artifact of a job running in a
        sandbox, which also records provenance linking the file to that execution,
        and pass an instrument_id for data captured off-platform by an instrument the
        Sync app cannot reach, which attaches the file to that instrument so
        instrument triggers and parsers pick it up.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        file : core.File
            See core.File for more documentation

        job_execution_id : typing.Optional[str]

        instrument_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileUploadSchema
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.files.upload()


        asyncio.run(main())
        """
        _response = await self._raw_client.upload(
            file=file, job_execution_id=job_execution_id, instrument_id=instrument_id, request_options=request_options
        )
        return _response.data

    async def get_content(
        self, file_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> FileContentSchema:
        """
        Fetch a source file's content for inspecting raw instrument output.

        Returns a presigned download URL plus a best-effort UTF-8 text preview of
        the start of the file. Large files return a URL only (no inline preview);
        fetch the full bytes via the URL when needed.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        file_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileContentSchema
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.files.get_content(
                file_id="file_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_content(file_id, request_options=request_options)
        return _response.data
