# This file was auto-generated by Fern from our API Definition.

import typing

from .. import core
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.file_content_schema import FileContentSchema
from ..types.file_info_schema import FileInfoSchema
from ..types.file_upload_schema import FileUploadSchema
from ..types.file_upload_url_schema import FileUploadUrlSchema
from .raw_client import AsyncRawFilesClient, RawFilesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class FilesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFilesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawFilesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFilesClient
        """
        return self._raw_client

    def list(
        self,
        *,
        instrument_id: typing.Optional[str] = None,
        extensions: typing.Optional[str] = None,
        query: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[FileInfoSchema]:
        """
        List source data files available for parser development.

        Returns the org's uploaded files, newest first.
        Filter by instrument_id, comma-separated file extensions (e.g. "csv,txt"),
        or a substring of the file name. Use the file-content tool to inspect a
        file's raw contents.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        instrument_id : typing.Optional[str]

        extensions : typing.Optional[str]

        query : typing.Optional[str]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[FileInfoSchema]
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.files.list()
        """
        _response = self._raw_client.list(
            instrument_id=instrument_id,
            extensions=extensions,
            query=query,
            limit=limit,
            request_options=request_options,
        )
        return _response.data

    def upload(
        self,
        *,
        file: core.File,
        job_execution_id: typing.Optional[str] = OMIT,
        instrument_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FileUploadSchema:
        """
        Upload a file in one multipart/form-data request.

        Request bodies over 4.5 MB are rejected at the platform edge before they
        reach this route. For larger files, create an upload URL and PUT the bytes
        to it instead; the SDK's files.upload() does that for files of any size.
        The [Upload files](https://docs.labric.co/upload-files) guide walks
        through both flows.

        At least one of job_execution_id and instrument_id is required: pass a
        job_execution_id for an artifact of a job running in a sandbox, which also
        records provenance linking the file to that execution, and pass an
        instrument_id for data captured off-platform by an instrument the Sync app
        cannot reach, which attaches the file to that instrument so instrument
        triggers and parsers pick it up.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        file : core.File
            See core.File for more documentation

        job_execution_id : typing.Optional[str]

        instrument_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileUploadSchema
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.files.upload()
        """
        _response = self._raw_client.upload(
            file=file, job_execution_id=job_execution_id, instrument_id=instrument_id, request_options=request_options
        )
        return _response.data

    def create_upload_url(
        self,
        *,
        file_name: str,
        content_type: typing.Optional[str] = OMIT,
        job_execution_id: typing.Optional[str] = OMIT,
        instrument_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FileUploadUrlSchema:
        """
        Start an upload that sends the file bytes straight to storage.

        Creates the file record and returns a signed URL that accepts the bytes as
        the body of an HTTP PUT for the next 15 minutes. Send exactly the returned
        headers on the PUT and no Authorization header, then confirm the upload to
        make the file visible. The URL only creates the object, never replaces one,
        and refuses bodies over 500 MB. Asking again for an instrument path whose
        upload was never confirmed returns a fresh URL for the same file, so a
        failed PUT can be retried. The SDK's files.upload() runs all three steps;
        the [Upload files](https://docs.labric.co/upload-files) guide shows them
        with curl.

        At least one of job_execution_id and instrument_id is required: pass a
        job_execution_id for an artifact of a job running in a sandbox, which also
        records provenance linking the file to that execution, and pass an
        instrument_id for data captured off-platform by an instrument the Sync app
        cannot reach, which attaches the file to that instrument so instrument
        triggers and parsers pick it up.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        file_name : str
            The file name to record, e.g. results.csv.

        content_type : typing.Optional[str]
            MIME type of the file. Defaults to application/octet-stream, which is also substituted for types a browser could render as a page.

        job_execution_id : typing.Optional[str]
            The job execution producing the file, for a job artifact.

        instrument_id : typing.Optional[str]
            The instrument that captured the file, for off-platform data.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileUploadUrlSchema
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.files.create_upload_url(
            file_name="file_name",
        )
        """
        _response = self._raw_client.create_upload_url(
            file_name=file_name,
            content_type=content_type,
            job_execution_id=job_execution_id,
            instrument_id=instrument_id,
            request_options=request_options,
        )
        return _response.data

    def confirm_upload(
        self, file_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> FileUploadSchema:
        """
        Finish an upload after the PUT to its upload URL has succeeded.

        Records the stored file's size and checksum, makes the file visible in
        listings, and notifies triggers and parsers. Files over 500 MB and native
        executables are discarded with a 400, as the one-request upload rejects
        them. Confirming a file that is already confirmed returns its record again
        without notifying anyone twice. The
        [Upload files](https://docs.labric.co/upload-files) guide shows the full
        sequence.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        file_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileUploadSchema
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.files.confirm_upload(
            file_id="file_id",
        )
        """
        _response = self._raw_client.confirm_upload(file_id, request_options=request_options)
        return _response.data

    def get_content(
        self, file_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> FileContentSchema:
        """
        Fetch a source file's content for inspecting raw instrument output.

        Returns a presigned download URL plus a best-effort UTF-8 text preview of
        the start of the file. Large files return a URL only (no inline preview);
        fetch the full bytes via the URL when needed.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        file_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileContentSchema
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.files.get_content(
            file_id="file_id",
        )
        """
        _response = self._raw_client.get_content(file_id, request_options=request_options)
        return _response.data


class AsyncFilesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFilesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawFilesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFilesClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        instrument_id: typing.Optional[str] = None,
        extensions: typing.Optional[str] = None,
        query: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[FileInfoSchema]:
        """
        List source data files available for parser development.

        Returns the org's uploaded files, newest first.
        Filter by instrument_id, comma-separated file extensions (e.g. "csv,txt"),
        or a substring of the file name. Use the file-content tool to inspect a
        file's raw contents.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        instrument_id : typing.Optional[str]

        extensions : typing.Optional[str]

        query : typing.Optional[str]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[FileInfoSchema]
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.files.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            instrument_id=instrument_id,
            extensions=extensions,
            query=query,
            limit=limit,
            request_options=request_options,
        )
        return _response.data

    async def upload(
        self,
        *,
        file: core.File,
        job_execution_id: typing.Optional[str] = OMIT,
        instrument_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FileUploadSchema:
        """
        Upload a file in one multipart/form-data request.

        Request bodies over 4.5 MB are rejected at the platform edge before they
        reach this route. For larger files, create an upload URL and PUT the bytes
        to it instead; the SDK's files.upload() does that for files of any size.
        The [Upload files](https://docs.labric.co/upload-files) guide walks
        through both flows.

        At least one of job_execution_id and instrument_id is required: pass a
        job_execution_id for an artifact of a job running in a sandbox, which also
        records provenance linking the file to that execution, and pass an
        instrument_id for data captured off-platform by an instrument the Sync app
        cannot reach, which attaches the file to that instrument so instrument
        triggers and parsers pick it up.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        file : core.File
            See core.File for more documentation

        job_execution_id : typing.Optional[str]

        instrument_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileUploadSchema
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.files.upload()


        asyncio.run(main())
        """
        _response = await self._raw_client.upload(
            file=file, job_execution_id=job_execution_id, instrument_id=instrument_id, request_options=request_options
        )
        return _response.data

    async def create_upload_url(
        self,
        *,
        file_name: str,
        content_type: typing.Optional[str] = OMIT,
        job_execution_id: typing.Optional[str] = OMIT,
        instrument_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FileUploadUrlSchema:
        """
        Start an upload that sends the file bytes straight to storage.

        Creates the file record and returns a signed URL that accepts the bytes as
        the body of an HTTP PUT for the next 15 minutes. Send exactly the returned
        headers on the PUT and no Authorization header, then confirm the upload to
        make the file visible. The URL only creates the object, never replaces one,
        and refuses bodies over 500 MB. Asking again for an instrument path whose
        upload was never confirmed returns a fresh URL for the same file, so a
        failed PUT can be retried. The SDK's files.upload() runs all three steps;
        the [Upload files](https://docs.labric.co/upload-files) guide shows them
        with curl.

        At least one of job_execution_id and instrument_id is required: pass a
        job_execution_id for an artifact of a job running in a sandbox, which also
        records provenance linking the file to that execution, and pass an
        instrument_id for data captured off-platform by an instrument the Sync app
        cannot reach, which attaches the file to that instrument so instrument
        triggers and parsers pick it up.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        file_name : str
            The file name to record, e.g. results.csv.

        content_type : typing.Optional[str]
            MIME type of the file. Defaults to application/octet-stream, which is also substituted for types a browser could render as a page.

        job_execution_id : typing.Optional[str]
            The job execution producing the file, for a job artifact.

        instrument_id : typing.Optional[str]
            The instrument that captured the file, for off-platform data.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileUploadUrlSchema
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.files.create_upload_url(
                file_name="file_name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_upload_url(
            file_name=file_name,
            content_type=content_type,
            job_execution_id=job_execution_id,
            instrument_id=instrument_id,
            request_options=request_options,
        )
        return _response.data

    async def confirm_upload(
        self, file_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> FileUploadSchema:
        """
        Finish an upload after the PUT to its upload URL has succeeded.

        Records the stored file's size and checksum, makes the file visible in
        listings, and notifies triggers and parsers. Files over 500 MB and native
        executables are discarded with a 400, as the one-request upload rejects
        them. Confirming a file that is already confirmed returns its record again
        without notifying anyone twice. The
        [Upload files](https://docs.labric.co/upload-files) guide shows the full
        sequence.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        file_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileUploadSchema
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.files.confirm_upload(
                file_id="file_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.confirm_upload(file_id, request_options=request_options)
        return _response.data

    async def get_content(
        self, file_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> FileContentSchema:
        """
        Fetch a source file's content for inspecting raw instrument output.

        Returns a presigned download URL plus a best-effort UTF-8 text preview of
        the start of the file. Large files return a URL only (no inline preview);
        fetch the full bytes via the URL when needed.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        file_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileContentSchema
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.files.get_content(
                file_id="file_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_content(file_id, request_options=request_options)
        return _response.data
