# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.sent_notification_schema import SentNotificationSchema
from .raw_client import AsyncRawNotificationsClient, RawNotificationsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class NotificationsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawNotificationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawNotificationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawNotificationsClient
        """
        return self._raw_client

    def send(
        self,
        *,
        title: str,
        dedupe_key: str,
        body: typing.Optional[str] = OMIT,
        action_url: typing.Optional[str] = OMIT,
        data: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SentNotificationSchema:
        """
        Send a message to your own inbox, and to your email if you have enabled
        email for the Message category in your notification preferences. Sends are
        capped per hour and per organization per day; a 429 response carries a
        Retry-After header. Messages sent with an API key are attributed to it, so
        the recipient can tell where they came from.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        title : str

        dedupe_key : str
            Idempotency key; a repeat send with the same key is dropped

        body : typing.Optional[str]

        action_url : typing.Optional[str]
            Platform path the notification opens, such as /jobs/<id>

        data : typing.Optional[typing.Dict[str, typing.Any]]
            Structured context stored with the notification. The keys sender and api_key_id are reserved for sender attribution.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SentNotificationSchema
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.notifications.send(
            title="title",
            dedupe_key="dedupe_key",
        )
        """
        _response = self._raw_client.send(
            title=title,
            dedupe_key=dedupe_key,
            body=body,
            action_url=action_url,
            data=data,
            request_options=request_options,
        )
        return _response.data


class AsyncNotificationsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawNotificationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawNotificationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawNotificationsClient
        """
        return self._raw_client

    async def send(
        self,
        *,
        title: str,
        dedupe_key: str,
        body: typing.Optional[str] = OMIT,
        action_url: typing.Optional[str] = OMIT,
        data: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SentNotificationSchema:
        """
        Send a message to your own inbox, and to your email if you have enabled
        email for the Message category in your notification preferences. Sends are
        capped per hour and per organization per day; a 429 response carries a
        Retry-After header. Messages sent with an API key are attributed to it, so
        the recipient can tell where they came from.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        title : str

        dedupe_key : str
            Idempotency key; a repeat send with the same key is dropped

        body : typing.Optional[str]

        action_url : typing.Optional[str]
            Platform path the notification opens, such as /jobs/<id>

        data : typing.Optional[typing.Dict[str, typing.Any]]
            Structured context stored with the notification. The keys sender and api_key_id are reserved for sender attribution.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SentNotificationSchema
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.notifications.send(
                title="title",
                dedupe_key="dedupe_key",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.send(
            title=title,
            dedupe_key=dedupe_key,
            body=body,
            action_url=action_url,
            data=data,
            request_options=request_options,
        )
        return _response.data
