# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.batch_write_options import BatchWriteOptions
from ..types.batch_write_response import BatchWriteResponse
from ..types.query_result import QueryResult
from ..types.table_schema_info_schema import TableSchemaInfoSchema
from .raw_client import AsyncRawToolsClient, RawToolsClient
from .types.labric_read_schema_mode import LabricReadSchemaMode
from .types.labric_read_schema_target_type import LabricReadSchemaTargetType
from .types.labric_write_schema_target_type import LabricWriteSchemaTargetType

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ToolsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawToolsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawToolsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawToolsClient
        """
        return self._raw_client

    def write(
        self,
        *,
        target_name: str,
        target_type: LabricWriteSchemaTargetType,
        data: typing.Sequence[typing.Dict[str, typing.Any]],
        mode: str,
        batch_insert_ok: typing.Optional[bool] = OMIT,
        params_to_match_for_update: typing.Optional[typing.Sequence[str]] = OMIT,
        defaults: typing.Optional[typing.Dict[str, typing.Optional[str]]] = OMIT,
        job_execution_id: typing.Optional[str] = OMIT,
        job_name: typing.Optional[str] = OMIT,
        collect_output: typing.Optional[bool] = OMIT,
        dry_run: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[typing.Dict[str, typing.Any]]:
        """
        Write records to a table.

        Inserts or updates records in the specified target table. Supports batch
        inserts, upserts with match columns, default value functions (DATETIME_NOW,
        UUID4), and optional dry-run validation. A job execution is created
        automatically if one is not provided.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        target_name : str
            The name of the table to write to.

        target_type : LabricWriteSchemaTargetType
            The type of target. Currently 'table' or 'core-table'.

        data : typing.Sequence[typing.Dict[str, typing.Any]]
            List of record dicts to write.

        mode : str
            Write mode (e.g. 'create', 'create-or-update').

        batch_insert_ok : typing.Optional[bool]
            If True, allow batch insert of multiple records.

        params_to_match_for_update : typing.Optional[typing.Sequence[str]]
            Column names to match on when updating existing records.

        defaults : typing.Optional[typing.Dict[str, typing.Optional[str]]]
            Map of field names to default function names (e.g. 'DATETIME_NOW', 'UUID4').

        job_execution_id : typing.Optional[str]
            Existing job execution ID to associate with this write. If omitted, a new one is created.

        job_name : typing.Optional[str]
            Name for the auto-created job. Defaults to 'Off-Platform Manual Job'.

        collect_output : typing.Optional[bool]
            If True, return the written records in the response.

        dry_run : typing.Optional[bool]
            If True, resolve references, check table and column validity, and return the execution plan without committing changes.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[typing.Dict[str, typing.Any]]
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.tools.write(
            target_name="target_name",
            target_type="table",
            data=[{"key": "value"}],
            mode="mode",
        )
        """
        _response = self._raw_client.write(
            target_name=target_name,
            target_type=target_type,
            data=data,
            mode=mode,
            batch_insert_ok=batch_insert_ok,
            params_to_match_for_update=params_to_match_for_update,
            defaults=defaults,
            job_execution_id=job_execution_id,
            job_name=job_name,
            collect_output=collect_output,
            dry_run=dry_run,
            request_options=request_options,
        )
        return _response.data

    def read(
        self,
        *,
        target_name: str,
        target_type: LabricReadSchemaTargetType,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        mode: typing.Optional[LabricReadSchemaMode] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[typing.Dict[str, typing.Any]]:
        """
        Read records from a table.

        Returns records from the specified table matching the given filters.
        Use 'single' mode to retrieve exactly one record, or 'multiple' mode
        to retrieve all matching records.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        target_name : str
            The name of the table to read from.

        target_type : LabricReadSchemaTargetType
            The type of target. Either 'table' or 'core-table'.

        filters : typing.Optional[typing.Dict[str, typing.Any]]
            Key-value filters to apply to the query. Omit to match all records.

        mode : typing.Optional[LabricReadSchemaMode]
            'single' returns exactly one record and throws an error if more than one matching record exists, 'multiple' returns all matches.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[typing.Dict[str, typing.Any]]
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.tools.read(
            target_name="target_name",
            target_type="table",
        )
        """
        _response = self._raw_client.read(
            target_name=target_name,
            target_type=target_type,
            filters=filters,
            mode=mode,
            request_options=request_options,
        )
        return _response.data

    def execute_sql(
        self,
        *,
        query: str,
        params: typing.Optional[typing.Sequence[typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> QueryResult:
        """
        Execute a read-only SQL query.

        Runs the query against the organization's read replica, so it cannot
        mutate data. Only SELECT statements are accepted. Supports positional
        parameters: write %s placeholders in the query and pass the values in
        order in the params list. Named :param placeholders belong to saved
        dataset queries and are not accepted here. Use the schema tool to discover tables
        first, and reference each column by its sql_column_name — foreign keys
        carry an _id suffix in SQL (e.g. a 'sample' reference is the 'sample_id'
        column).

        Requires an API key with the `read` scope.

        Parameters
        ----------
        query : str

        params : typing.Optional[typing.Sequence[typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        QueryResult
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.tools.execute_sql(
            query="query",
        )
        """
        _response = self._raw_client.execute_sql(query=query, params=params, request_options=request_options)
        return _response.data

    def get_schema(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[TableSchemaInfoSchema]:
        """
        Describe the organization's data schema.

        Returns every table the agent can target, including its semantic category
        (e.g. raw vs. curated), description, and full column definitions with types,
        nullability, uniqueness, and foreign-key targets. Each column carries two
        names: 'name' is what the read and write tools accept, and 'sql_column_name'
        is the physical column for SQL queries (foreign keys carry an _id suffix).
        This is the map a parser writes into: use it to plan which tables to
        populate and how rows link.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[TableSchemaInfoSchema]
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.tools.get_schema()
        """
        _response = self._raw_client.get_schema(request_options=request_options)
        return _response.data

    def batch_write(
        self,
        *,
        tables: typing.Dict[str, typing.Sequence[typing.Dict[str, typing.Any]]],
        options: typing.Optional[BatchWriteOptions] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BatchWriteResponse:
        """
        Write records to multiple tables in a single transaction.

        Supports:
        - Batch references: Use "_ref" to label records, "@refname" to reference them
        - Natural keys: Use human-readable values for foreign keys (e.g., recipe name)
        - Automatic FK ordering: Tables are inserted in dependency order
        - Upsert mode: Update existing records based on match columns
        - Dry run: Validate without committing changes

        Committed writes are recorded against a job execution (created automatically
        if not supplied) and the job_execution_id is returned, so the write can be
        reverted as a unit.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        tables : typing.Dict[str, typing.Sequence[typing.Dict[str, typing.Any]]]
            Map of table_name to list of records to insert.

        options : typing.Optional[BatchWriteOptions]
            Optional write options (mode, match_on, dry_run, return_records).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchWriteResponse
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.tools.batch_write(
            tables={"key": [{"key": "value"}]},
        )
        """
        _response = self._raw_client.batch_write(tables=tables, options=options, request_options=request_options)
        return _response.data


class AsyncToolsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawToolsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawToolsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawToolsClient
        """
        return self._raw_client

    async def write(
        self,
        *,
        target_name: str,
        target_type: LabricWriteSchemaTargetType,
        data: typing.Sequence[typing.Dict[str, typing.Any]],
        mode: str,
        batch_insert_ok: typing.Optional[bool] = OMIT,
        params_to_match_for_update: typing.Optional[typing.Sequence[str]] = OMIT,
        defaults: typing.Optional[typing.Dict[str, typing.Optional[str]]] = OMIT,
        job_execution_id: typing.Optional[str] = OMIT,
        job_name: typing.Optional[str] = OMIT,
        collect_output: typing.Optional[bool] = OMIT,
        dry_run: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[typing.Dict[str, typing.Any]]:
        """
        Write records to a table.

        Inserts or updates records in the specified target table. Supports batch
        inserts, upserts with match columns, default value functions (DATETIME_NOW,
        UUID4), and optional dry-run validation. A job execution is created
        automatically if one is not provided.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        target_name : str
            The name of the table to write to.

        target_type : LabricWriteSchemaTargetType
            The type of target. Currently 'table' or 'core-table'.

        data : typing.Sequence[typing.Dict[str, typing.Any]]
            List of record dicts to write.

        mode : str
            Write mode (e.g. 'create', 'create-or-update').

        batch_insert_ok : typing.Optional[bool]
            If True, allow batch insert of multiple records.

        params_to_match_for_update : typing.Optional[typing.Sequence[str]]
            Column names to match on when updating existing records.

        defaults : typing.Optional[typing.Dict[str, typing.Optional[str]]]
            Map of field names to default function names (e.g. 'DATETIME_NOW', 'UUID4').

        job_execution_id : typing.Optional[str]
            Existing job execution ID to associate with this write. If omitted, a new one is created.

        job_name : typing.Optional[str]
            Name for the auto-created job. Defaults to 'Off-Platform Manual Job'.

        collect_output : typing.Optional[bool]
            If True, return the written records in the response.

        dry_run : typing.Optional[bool]
            If True, resolve references, check table and column validity, and return the execution plan without committing changes.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[typing.Dict[str, typing.Any]]
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tools.write(
                target_name="target_name",
                target_type="table",
                data=[{"key": "value"}],
                mode="mode",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.write(
            target_name=target_name,
            target_type=target_type,
            data=data,
            mode=mode,
            batch_insert_ok=batch_insert_ok,
            params_to_match_for_update=params_to_match_for_update,
            defaults=defaults,
            job_execution_id=job_execution_id,
            job_name=job_name,
            collect_output=collect_output,
            dry_run=dry_run,
            request_options=request_options,
        )
        return _response.data

    async def read(
        self,
        *,
        target_name: str,
        target_type: LabricReadSchemaTargetType,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        mode: typing.Optional[LabricReadSchemaMode] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[typing.Dict[str, typing.Any]]:
        """
        Read records from a table.

        Returns records from the specified table matching the given filters.
        Use 'single' mode to retrieve exactly one record, or 'multiple' mode
        to retrieve all matching records.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        target_name : str
            The name of the table to read from.

        target_type : LabricReadSchemaTargetType
            The type of target. Either 'table' or 'core-table'.

        filters : typing.Optional[typing.Dict[str, typing.Any]]
            Key-value filters to apply to the query. Omit to match all records.

        mode : typing.Optional[LabricReadSchemaMode]
            'single' returns exactly one record and throws an error if more than one matching record exists, 'multiple' returns all matches.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[typing.Dict[str, typing.Any]]
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tools.read(
                target_name="target_name",
                target_type="table",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.read(
            target_name=target_name,
            target_type=target_type,
            filters=filters,
            mode=mode,
            request_options=request_options,
        )
        return _response.data

    async def execute_sql(
        self,
        *,
        query: str,
        params: typing.Optional[typing.Sequence[typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> QueryResult:
        """
        Execute a read-only SQL query.

        Runs the query against the organization's read replica, so it cannot
        mutate data. Only SELECT statements are accepted. Supports positional
        parameters: write %s placeholders in the query and pass the values in
        order in the params list. Named :param placeholders belong to saved
        dataset queries and are not accepted here. Use the schema tool to discover tables
        first, and reference each column by its sql_column_name — foreign keys
        carry an _id suffix in SQL (e.g. a 'sample' reference is the 'sample_id'
        column).

        Requires an API key with the `read` scope.

        Parameters
        ----------
        query : str

        params : typing.Optional[typing.Sequence[typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        QueryResult
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tools.execute_sql(
                query="query",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.execute_sql(query=query, params=params, request_options=request_options)
        return _response.data

    async def get_schema(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[TableSchemaInfoSchema]:
        """
        Describe the organization's data schema.

        Returns every table the agent can target, including its semantic category
        (e.g. raw vs. curated), description, and full column definitions with types,
        nullability, uniqueness, and foreign-key targets. Each column carries two
        names: 'name' is what the read and write tools accept, and 'sql_column_name'
        is the physical column for SQL queries (foreign keys carry an _id suffix).
        This is the map a parser writes into: use it to plan which tables to
        populate and how rows link.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[TableSchemaInfoSchema]
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tools.get_schema()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_schema(request_options=request_options)
        return _response.data

    async def batch_write(
        self,
        *,
        tables: typing.Dict[str, typing.Sequence[typing.Dict[str, typing.Any]]],
        options: typing.Optional[BatchWriteOptions] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BatchWriteResponse:
        """
        Write records to multiple tables in a single transaction.

        Supports:
        - Batch references: Use "_ref" to label records, "@refname" to reference them
        - Natural keys: Use human-readable values for foreign keys (e.g., recipe name)
        - Automatic FK ordering: Tables are inserted in dependency order
        - Upsert mode: Update existing records based on match columns
        - Dry run: Validate without committing changes

        Committed writes are recorded against a job execution (created automatically
        if not supplied) and the job_execution_id is returned, so the write can be
        reverted as a unit.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        tables : typing.Dict[str, typing.Sequence[typing.Dict[str, typing.Any]]]
            Map of table_name to list of records to insert.

        options : typing.Optional[BatchWriteOptions]
            Optional write options (mode, match_on, dry_run, return_records).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchWriteResponse
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tools.batch_write(
                tables={"key": [{"key": "value"}]},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.batch_write(tables=tables, options=options, request_options=request_options)
        return _response.data
