# This file was auto-generated by Fern from our API Definition.

import typing

from .. import core
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.batch_write_options import BatchWriteOptions
from ..types.batch_write_response import BatchWriteResponse
from ..types.labric_upload_file_schema import LabricUploadFileSchema
from ..types.predict_response_schema import PredictResponseSchema
from ..types.query_result import QueryResult
from ..types.revert_result_schema import RevertResultSchema
from ..types.start_job_execution_schema import StartJobExecutionSchema
from ..types.table_schema_info_schema import TableSchemaInfoSchema
from ..types.tools_file_content_schema import ToolsFileContentSchema
from ..types.tools_file_info_schema import ToolsFileInfoSchema
from ..types.tools_job_execution_schema import ToolsJobExecutionSchema
from ..types.tools_ml_model_schema import ToolsMlModelSchema
from .raw_client import AsyncRawToolsClient, RawToolsClient
from .types.labric_read_schema_mode import LabricReadSchemaMode
from .types.labric_read_schema_target_type import LabricReadSchemaTargetType
from .types.labric_write_schema_target_type import LabricWriteSchemaTargetType
from .types.update_job_execution_status_schema_status import UpdateJobExecutionStatusSchemaStatus

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ToolsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawToolsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawToolsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawToolsClient
        """
        return self._raw_client

    def write(
        self,
        *,
        target_name: str,
        target_type: LabricWriteSchemaTargetType,
        data: typing.Sequence[typing.Dict[str, typing.Any]],
        mode: str,
        batch_insert_ok: typing.Optional[bool] = OMIT,
        params_to_match_for_update: typing.Optional[typing.Sequence[str]] = OMIT,
        defaults: typing.Optional[typing.Dict[str, typing.Optional[str]]] = OMIT,
        job_execution_id: typing.Optional[str] = OMIT,
        job_name: typing.Optional[str] = OMIT,
        collect_output: typing.Optional[bool] = OMIT,
        dry_run: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[typing.Dict[str, typing.Any]]:
        """
        Write records to a table.

        Inserts or updates records in the specified target table. Supports batch
        inserts, upserts with match columns, default value functions (DATETIME_NOW,
        UUID4), and optional dry-run validation. A job execution is created
        automatically if one is not provided.

        Parameters
        ----------
        target_name : str
            The name of the table to write to.

        target_type : LabricWriteSchemaTargetType
            The type of target. Currently 'table' or 'core-table'.

        data : typing.Sequence[typing.Dict[str, typing.Any]]
            List of record dicts to write.

        mode : str
            Write mode (e.g. 'create', 'create-or-update').

        batch_insert_ok : typing.Optional[bool]
            If True, allow batch insert of multiple records.

        params_to_match_for_update : typing.Optional[typing.Sequence[str]]
            Column names to match on when updating existing records.

        defaults : typing.Optional[typing.Dict[str, typing.Optional[str]]]
            Map of field names to default function names (e.g. 'DATETIME_NOW', 'UUID4').

        job_execution_id : typing.Optional[str]
            Existing job execution ID to associate with this write. If omitted, a new one is created.

        job_name : typing.Optional[str]
            Name for the auto-created job. Defaults to 'Off-Platform Manual Job'.

        collect_output : typing.Optional[bool]
            If True, return the written records in the response.

        dry_run : typing.Optional[bool]
            If True, resolve references, check table and column validity, and return the execution plan without committing changes.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[typing.Dict[str, typing.Any]]
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.tools.write(
            target_name="target_name",
            target_type="table",
            data=[{"key": "value"}],
            mode="mode",
        )
        """
        _response = self._raw_client.write(
            target_name=target_name,
            target_type=target_type,
            data=data,
            mode=mode,
            batch_insert_ok=batch_insert_ok,
            params_to_match_for_update=params_to_match_for_update,
            defaults=defaults,
            job_execution_id=job_execution_id,
            job_name=job_name,
            collect_output=collect_output,
            dry_run=dry_run,
            request_options=request_options,
        )
        return _response.data

    def read(
        self,
        *,
        target_name: str,
        target_type: LabricReadSchemaTargetType,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        mode: typing.Optional[LabricReadSchemaMode] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[typing.Dict[str, typing.Any]]:
        """
        Read records from a table.

        Returns records from the specified table matching the given filters.
        Use 'single' mode to retrieve exactly one record, or 'multiple' mode
        to retrieve all matching records.

        Parameters
        ----------
        target_name : str
            The name of the table to read from.

        target_type : LabricReadSchemaTargetType
            The type of target. Either 'table' or 'core-table'.

        filters : typing.Optional[typing.Dict[str, typing.Any]]
            Key-value filters to apply to the query. Omit to match all records.

        mode : typing.Optional[LabricReadSchemaMode]
            'single' returns exactly one record and throws an error if more than one matching record exists, 'multiple' returns all matches.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[typing.Dict[str, typing.Any]]
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.tools.read(
            target_name="target_name",
            target_type="table",
        )
        """
        _response = self._raw_client.read(
            target_name=target_name,
            target_type=target_type,
            filters=filters,
            mode=mode,
            request_options=request_options,
        )
        return _response.data

    def execute_sql(
        self,
        *,
        query: str,
        params: typing.Optional[typing.Sequence[typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> QueryResult:
        """
        Execute a read-only SQL query.

        Runs the query against the organization's read replica, so it cannot
        mutate data. Only SELECT statements are accepted. Supports positional
        parameters via a params list. Use the schema tool to discover tables
        first, and reference each column by its sql_column_name — foreign keys
        carry an _id suffix in SQL (e.g. a 'sample' reference is the 'sample_id'
        column).

        Parameters
        ----------
        query : str

        params : typing.Optional[typing.Sequence[typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        QueryResult
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.tools.execute_sql(
            query="query",
        )
        """
        _response = self._raw_client.execute_sql(query=query, params=params, request_options=request_options)
        return _response.data

    def upload_file(
        self,
        *,
        file: core.File,
        job_execution_id: typing.Optional[str] = OMIT,
        instrument_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> LabricUploadFileSchema:
        """
        Upload a file.

        Accepts a multipart/form-data file upload, stores it in GCS, and returns the
        created file record. At least one of job_execution_id and instrument_id is
        required: pass a job_execution_id for an artifact of a job running in a
        sandbox, which also records provenance linking the file to that execution,
        and pass an instrument_id for data captured off-platform by an instrument the
        Sync app cannot reach, which attaches the file to that instrument so
        instrument triggers and parsers pick it up.

        Parameters
        ----------
        file : core.File
            See core.File for more documentation

        job_execution_id : typing.Optional[str]

        instrument_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LabricUploadFileSchema
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.tools.upload_file()
        """
        _response = self._raw_client.upload_file(
            file=file, job_execution_id=job_execution_id, instrument_id=instrument_id, request_options=request_options
        )
        return _response.data

    def get_schema(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[TableSchemaInfoSchema]:
        """
        Describe the organization's data schema.

        Returns every table the agent can target, including its semantic category
        (e.g. raw vs. curated), description, and full column definitions with types,
        nullability, uniqueness, and foreign-key targets. Each column carries two
        names: 'name' is what the read and write tools accept, and 'sql_column_name'
        is the physical column for SQL queries (foreign keys carry an _id suffix).
        This is the map a parser writes into: use it to plan which tables to
        populate and how rows link.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[TableSchemaInfoSchema]
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.tools.get_schema()
        """
        _response = self._raw_client.get_schema(request_options=request_options)
        return _response.data

    def list_files(
        self,
        *,
        instrument_id: typing.Optional[str] = None,
        extensions: typing.Optional[str] = None,
        query: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[ToolsFileInfoSchema]:
        """
        List source data files available for parser development.

        Returns a representative set of uploaded files for the org, newest first.
        Filter by instrument_id, comma-separated file extensions (e.g. "csv,txt"),
        or a substring of the file name. Use the file-content tool to inspect a
        file's raw contents.

        Parameters
        ----------
        instrument_id : typing.Optional[str]

        extensions : typing.Optional[str]

        query : typing.Optional[str]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ToolsFileInfoSchema]
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.tools.list_files()
        """
        _response = self._raw_client.list_files(
            instrument_id=instrument_id,
            extensions=extensions,
            query=query,
            limit=limit,
            request_options=request_options,
        )
        return _response.data

    def get_file_content(
        self, file_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ToolsFileContentSchema:
        """
        Fetch a source file's content for inspecting raw instrument output.

        Returns a presigned download URL plus a best-effort UTF-8 text preview of
        the start of the file. Large files return a URL only (no inline preview);
        fetch the full bytes via the URL when needed.

        Parameters
        ----------
        file_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ToolsFileContentSchema
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.tools.get_file_content(
            file_id="file_id",
        )
        """
        _response = self._raw_client.get_file_content(file_id, request_options=request_options)
        return _response.data

    def start_job_execution(
        self,
        *,
        request: typing.Optional[StartJobExecutionSchema] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ToolsJobExecutionSchema:
        """
        Open a job execution for a script running outside the platform.

        Returns a job_execution_id to pass to the write and upload-file tools, so
        everything a single script run produces is attributed to one execution and
        can be inspected or reverted as a unit. Run under an existing job by passing
        its job_id, or pass a job_name to run under a job of that name, creating it
        if it does not exist; with neither, the execution lands under a default
        off-platform job. The execution is marked running immediately; close it with
        the update-status tool when the script finishes. Pass timeout_minutes to
        have the platform fail the execution after that duration elapses, if the
        script has not closed it in time. This prevents crashed scripts from
        leaving jobs marked as running forever on the platform.

        Parameters
        ----------
        request : typing.Optional[StartJobExecutionSchema]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ToolsJobExecutionSchema
            OK

        Examples
        --------
        from labric import Labric, StartJobExecutionSchema

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.tools.start_job_execution(
            request=StartJobExecutionSchema(),
        )
        """
        _response = self._raw_client.start_job_execution(request=request, request_options=request_options)
        return _response.data

    def update_job_execution_status(
        self,
        execution_id: str,
        *,
        status: UpdateJobExecutionStatusSchemaStatus,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ToolsJobExecutionSchema:
        """
        Close a job execution as completed or failed.

        Use this when an off-platform script finishes, so the platform stops
        reporting the run as in progress. Either status is final: re-sending the
        status the execution already has is a no-op, but changing it afterwards is
        rejected. Only executions opened by the start tool are accepted — every
        other execution's status is recorded by the platform itself.

        Parameters
        ----------
        execution_id : str

        status : UpdateJobExecutionStatusSchemaStatus
            How the run ended. Either status is final: the execution cannot change status afterwards.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ToolsJobExecutionSchema
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.tools.update_job_execution_status(
            execution_id="execution_id",
            status="completed",
        )
        """
        _response = self._raw_client.update_job_execution_status(
            execution_id, status=status, request_options=request_options
        )
        return _response.data

    def revert_job_execution(
        self, execution_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RevertResultSchema:
        """
        Revert a test parse by deleting the rows it created.

        Deletes the CREATE'd objects of a job execution and their linked raw rows,
        in a single transaction. Use this to undo a test write whose validation
        failed. UPDATE and DELETE operations cannot be reversed and are surfaced as
        warnings in the result.

        Parameters
        ----------
        execution_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RevertResultSchema
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.tools.revert_job_execution(
            execution_id="execution_id",
        )
        """
        _response = self._raw_client.revert_job_execution(execution_id, request_options=request_options)
        return _response.data

    def batch_write(
        self,
        *,
        tables: typing.Dict[str, typing.Sequence[typing.Dict[str, typing.Any]]],
        options: typing.Optional[BatchWriteOptions] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BatchWriteResponse:
        """
        Write records to multiple tables in a single transaction.

        Supports:
        - Batch references: Use "_ref" to label records, "@refname" to reference them
        - Natural keys: Use human-readable values for foreign keys (e.g., recipe name)
        - Automatic FK ordering: Tables are inserted in dependency order
        - Upsert mode: Update existing records based on match columns
        - Dry run: Validate without committing changes

        Committed writes are recorded against a job execution (created automatically
        if not supplied) and the job_execution_id is returned, so the write can be
        reverted as a unit.

        Parameters
        ----------
        tables : typing.Dict[str, typing.Sequence[typing.Dict[str, typing.Any]]]
            Map of table_name to list of records to insert.

        options : typing.Optional[BatchWriteOptions]
            Optional write options (mode, match_on, dry_run, return_records).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchWriteResponse
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.tools.batch_write(
            tables={"key": [{"key": "value"}]},
        )
        """
        _response = self._raw_client.batch_write(tables=tables, options=options, request_options=request_options)
        return _response.data

    def predict(
        self,
        *,
        data: typing.Sequence[typing.Dict[str, typing.Any]],
        ml_model_id: typing.Optional[str] = OMIT,
        ml_model_name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PredictResponseSchema:
        """
        Run predictions with a trained ML model.

        Identify the model by ml_model_id, or by ml_model_name (the name of a
        non-archived model). Each row in data maps the model's feature columns to
        values -- use the ml-models tool to discover models and the columns each
        expects. Returns one prediction per input row, plus per-class
        probabilities for classifiers.

        Parameters
        ----------
        data : typing.Sequence[typing.Dict[str, typing.Any]]

        ml_model_id : typing.Optional[str]

        ml_model_name : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PredictResponseSchema
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.tools.predict(
            data=[{"key": "value"}],
        )
        """
        _response = self._raw_client.predict(
            data=data, ml_model_id=ml_model_id, ml_model_name=ml_model_name, request_options=request_options
        )
        return _response.data

    def list_ml_models(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[ToolsMlModelSchema]:
        """
        List the organization's ML models and the inputs each expects.

        Returns each non-archived model with its serving status and prediction
        interface: feature_columns (plus image_columns for image models) are the
        fields each data row passed to the predict tool should contain, and
        target_column is what the model predicts. Only models with status 'ready'
        can serve predictions.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ToolsMlModelSchema]
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.tools.list_ml_models()
        """
        _response = self._raw_client.list_ml_models(request_options=request_options)
        return _response.data


class AsyncToolsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawToolsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawToolsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawToolsClient
        """
        return self._raw_client

    async def write(
        self,
        *,
        target_name: str,
        target_type: LabricWriteSchemaTargetType,
        data: typing.Sequence[typing.Dict[str, typing.Any]],
        mode: str,
        batch_insert_ok: typing.Optional[bool] = OMIT,
        params_to_match_for_update: typing.Optional[typing.Sequence[str]] = OMIT,
        defaults: typing.Optional[typing.Dict[str, typing.Optional[str]]] = OMIT,
        job_execution_id: typing.Optional[str] = OMIT,
        job_name: typing.Optional[str] = OMIT,
        collect_output: typing.Optional[bool] = OMIT,
        dry_run: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[typing.Dict[str, typing.Any]]:
        """
        Write records to a table.

        Inserts or updates records in the specified target table. Supports batch
        inserts, upserts with match columns, default value functions (DATETIME_NOW,
        UUID4), and optional dry-run validation. A job execution is created
        automatically if one is not provided.

        Parameters
        ----------
        target_name : str
            The name of the table to write to.

        target_type : LabricWriteSchemaTargetType
            The type of target. Currently 'table' or 'core-table'.

        data : typing.Sequence[typing.Dict[str, typing.Any]]
            List of record dicts to write.

        mode : str
            Write mode (e.g. 'create', 'create-or-update').

        batch_insert_ok : typing.Optional[bool]
            If True, allow batch insert of multiple records.

        params_to_match_for_update : typing.Optional[typing.Sequence[str]]
            Column names to match on when updating existing records.

        defaults : typing.Optional[typing.Dict[str, typing.Optional[str]]]
            Map of field names to default function names (e.g. 'DATETIME_NOW', 'UUID4').

        job_execution_id : typing.Optional[str]
            Existing job execution ID to associate with this write. If omitted, a new one is created.

        job_name : typing.Optional[str]
            Name for the auto-created job. Defaults to 'Off-Platform Manual Job'.

        collect_output : typing.Optional[bool]
            If True, return the written records in the response.

        dry_run : typing.Optional[bool]
            If True, resolve references, check table and column validity, and return the execution plan without committing changes.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[typing.Dict[str, typing.Any]]
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tools.write(
                target_name="target_name",
                target_type="table",
                data=[{"key": "value"}],
                mode="mode",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.write(
            target_name=target_name,
            target_type=target_type,
            data=data,
            mode=mode,
            batch_insert_ok=batch_insert_ok,
            params_to_match_for_update=params_to_match_for_update,
            defaults=defaults,
            job_execution_id=job_execution_id,
            job_name=job_name,
            collect_output=collect_output,
            dry_run=dry_run,
            request_options=request_options,
        )
        return _response.data

    async def read(
        self,
        *,
        target_name: str,
        target_type: LabricReadSchemaTargetType,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        mode: typing.Optional[LabricReadSchemaMode] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[typing.Dict[str, typing.Any]]:
        """
        Read records from a table.

        Returns records from the specified table matching the given filters.
        Use 'single' mode to retrieve exactly one record, or 'multiple' mode
        to retrieve all matching records.

        Parameters
        ----------
        target_name : str
            The name of the table to read from.

        target_type : LabricReadSchemaTargetType
            The type of target. Either 'table' or 'core-table'.

        filters : typing.Optional[typing.Dict[str, typing.Any]]
            Key-value filters to apply to the query. Omit to match all records.

        mode : typing.Optional[LabricReadSchemaMode]
            'single' returns exactly one record and throws an error if more than one matching record exists, 'multiple' returns all matches.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[typing.Dict[str, typing.Any]]
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tools.read(
                target_name="target_name",
                target_type="table",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.read(
            target_name=target_name,
            target_type=target_type,
            filters=filters,
            mode=mode,
            request_options=request_options,
        )
        return _response.data

    async def execute_sql(
        self,
        *,
        query: str,
        params: typing.Optional[typing.Sequence[typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> QueryResult:
        """
        Execute a read-only SQL query.

        Runs the query against the organization's read replica, so it cannot
        mutate data. Only SELECT statements are accepted. Supports positional
        parameters via a params list. Use the schema tool to discover tables
        first, and reference each column by its sql_column_name — foreign keys
        carry an _id suffix in SQL (e.g. a 'sample' reference is the 'sample_id'
        column).

        Parameters
        ----------
        query : str

        params : typing.Optional[typing.Sequence[typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        QueryResult
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tools.execute_sql(
                query="query",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.execute_sql(query=query, params=params, request_options=request_options)
        return _response.data

    async def upload_file(
        self,
        *,
        file: core.File,
        job_execution_id: typing.Optional[str] = OMIT,
        instrument_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> LabricUploadFileSchema:
        """
        Upload a file.

        Accepts a multipart/form-data file upload, stores it in GCS, and returns the
        created file record. At least one of job_execution_id and instrument_id is
        required: pass a job_execution_id for an artifact of a job running in a
        sandbox, which also records provenance linking the file to that execution,
        and pass an instrument_id for data captured off-platform by an instrument the
        Sync app cannot reach, which attaches the file to that instrument so
        instrument triggers and parsers pick it up.

        Parameters
        ----------
        file : core.File
            See core.File for more documentation

        job_execution_id : typing.Optional[str]

        instrument_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LabricUploadFileSchema
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tools.upload_file()


        asyncio.run(main())
        """
        _response = await self._raw_client.upload_file(
            file=file, job_execution_id=job_execution_id, instrument_id=instrument_id, request_options=request_options
        )
        return _response.data

    async def get_schema(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[TableSchemaInfoSchema]:
        """
        Describe the organization's data schema.

        Returns every table the agent can target, including its semantic category
        (e.g. raw vs. curated), description, and full column definitions with types,
        nullability, uniqueness, and foreign-key targets. Each column carries two
        names: 'name' is what the read and write tools accept, and 'sql_column_name'
        is the physical column for SQL queries (foreign keys carry an _id suffix).
        This is the map a parser writes into: use it to plan which tables to
        populate and how rows link.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[TableSchemaInfoSchema]
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tools.get_schema()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_schema(request_options=request_options)
        return _response.data

    async def list_files(
        self,
        *,
        instrument_id: typing.Optional[str] = None,
        extensions: typing.Optional[str] = None,
        query: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[ToolsFileInfoSchema]:
        """
        List source data files available for parser development.

        Returns a representative set of uploaded files for the org, newest first.
        Filter by instrument_id, comma-separated file extensions (e.g. "csv,txt"),
        or a substring of the file name. Use the file-content tool to inspect a
        file's raw contents.

        Parameters
        ----------
        instrument_id : typing.Optional[str]

        extensions : typing.Optional[str]

        query : typing.Optional[str]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ToolsFileInfoSchema]
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tools.list_files()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_files(
            instrument_id=instrument_id,
            extensions=extensions,
            query=query,
            limit=limit,
            request_options=request_options,
        )
        return _response.data

    async def get_file_content(
        self, file_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ToolsFileContentSchema:
        """
        Fetch a source file's content for inspecting raw instrument output.

        Returns a presigned download URL plus a best-effort UTF-8 text preview of
        the start of the file. Large files return a URL only (no inline preview);
        fetch the full bytes via the URL when needed.

        Parameters
        ----------
        file_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ToolsFileContentSchema
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tools.get_file_content(
                file_id="file_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_file_content(file_id, request_options=request_options)
        return _response.data

    async def start_job_execution(
        self,
        *,
        request: typing.Optional[StartJobExecutionSchema] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ToolsJobExecutionSchema:
        """
        Open a job execution for a script running outside the platform.

        Returns a job_execution_id to pass to the write and upload-file tools, so
        everything a single script run produces is attributed to one execution and
        can be inspected or reverted as a unit. Run under an existing job by passing
        its job_id, or pass a job_name to run under a job of that name, creating it
        if it does not exist; with neither, the execution lands under a default
        off-platform job. The execution is marked running immediately; close it with
        the update-status tool when the script finishes. Pass timeout_minutes to
        have the platform fail the execution after that duration elapses, if the
        script has not closed it in time. This prevents crashed scripts from
        leaving jobs marked as running forever on the platform.

        Parameters
        ----------
        request : typing.Optional[StartJobExecutionSchema]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ToolsJobExecutionSchema
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric, StartJobExecutionSchema

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tools.start_job_execution(
                request=StartJobExecutionSchema(),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.start_job_execution(request=request, request_options=request_options)
        return _response.data

    async def update_job_execution_status(
        self,
        execution_id: str,
        *,
        status: UpdateJobExecutionStatusSchemaStatus,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ToolsJobExecutionSchema:
        """
        Close a job execution as completed or failed.

        Use this when an off-platform script finishes, so the platform stops
        reporting the run as in progress. Either status is final: re-sending the
        status the execution already has is a no-op, but changing it afterwards is
        rejected. Only executions opened by the start tool are accepted — every
        other execution's status is recorded by the platform itself.

        Parameters
        ----------
        execution_id : str

        status : UpdateJobExecutionStatusSchemaStatus
            How the run ended. Either status is final: the execution cannot change status afterwards.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ToolsJobExecutionSchema
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tools.update_job_execution_status(
                execution_id="execution_id",
                status="completed",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_job_execution_status(
            execution_id, status=status, request_options=request_options
        )
        return _response.data

    async def revert_job_execution(
        self, execution_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RevertResultSchema:
        """
        Revert a test parse by deleting the rows it created.

        Deletes the CREATE'd objects of a job execution and their linked raw rows,
        in a single transaction. Use this to undo a test write whose validation
        failed. UPDATE and DELETE operations cannot be reversed and are surfaced as
        warnings in the result.

        Parameters
        ----------
        execution_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RevertResultSchema
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tools.revert_job_execution(
                execution_id="execution_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.revert_job_execution(execution_id, request_options=request_options)
        return _response.data

    async def batch_write(
        self,
        *,
        tables: typing.Dict[str, typing.Sequence[typing.Dict[str, typing.Any]]],
        options: typing.Optional[BatchWriteOptions] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BatchWriteResponse:
        """
        Write records to multiple tables in a single transaction.

        Supports:
        - Batch references: Use "_ref" to label records, "@refname" to reference them
        - Natural keys: Use human-readable values for foreign keys (e.g., recipe name)
        - Automatic FK ordering: Tables are inserted in dependency order
        - Upsert mode: Update existing records based on match columns
        - Dry run: Validate without committing changes

        Committed writes are recorded against a job execution (created automatically
        if not supplied) and the job_execution_id is returned, so the write can be
        reverted as a unit.

        Parameters
        ----------
        tables : typing.Dict[str, typing.Sequence[typing.Dict[str, typing.Any]]]
            Map of table_name to list of records to insert.

        options : typing.Optional[BatchWriteOptions]
            Optional write options (mode, match_on, dry_run, return_records).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchWriteResponse
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tools.batch_write(
                tables={"key": [{"key": "value"}]},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.batch_write(tables=tables, options=options, request_options=request_options)
        return _response.data

    async def predict(
        self,
        *,
        data: typing.Sequence[typing.Dict[str, typing.Any]],
        ml_model_id: typing.Optional[str] = OMIT,
        ml_model_name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PredictResponseSchema:
        """
        Run predictions with a trained ML model.

        Identify the model by ml_model_id, or by ml_model_name (the name of a
        non-archived model). Each row in data maps the model's feature columns to
        values -- use the ml-models tool to discover models and the columns each
        expects. Returns one prediction per input row, plus per-class
        probabilities for classifiers.

        Parameters
        ----------
        data : typing.Sequence[typing.Dict[str, typing.Any]]

        ml_model_id : typing.Optional[str]

        ml_model_name : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PredictResponseSchema
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tools.predict(
                data=[{"key": "value"}],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.predict(
            data=data, ml_model_id=ml_model_id, ml_model_name=ml_model_name, request_options=request_options
        )
        return _response.data

    async def list_ml_models(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[ToolsMlModelSchema]:
        """
        List the organization's ML models and the inputs each expects.

        Returns each non-archived model with its serving status and prediction
        interface: feature_columns (plus image_columns for image models) are the
        fields each data row passed to the predict tool should contain, and
        target_column is what the model predicts. Only models with status 'ready'
        can serve predictions.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ToolsMlModelSchema]
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tools.list_ml_models()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_ml_models(request_options=request_options)
        return _response.data
