# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_request_error import BadRequestError
from ..errors.forbidden_error import ForbiddenError
from ..errors.internal_server_error import InternalServerError
from ..errors.not_found_error import NotFoundError
from ..errors.service_unavailable_error import ServiceUnavailableError
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.batch_write_options import BatchWriteOptions
from ..types.batch_write_response import BatchWriteResponse
from ..types.error_schema import ErrorSchema
from ..types.query_result import QueryResult
from ..types.queryable_table_schema import QueryableTableSchema
from ..types.validation_error_schema import ValidationErrorSchema
from .types.labric_read_schema_mode import LabricReadSchemaMode
from .types.labric_read_schema_target_type import LabricReadSchemaTargetType
from .types.labric_write_schema_target_type import LabricWriteSchemaTargetType
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawToolsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def write(
        self,
        *,
        target_name: str,
        target_type: LabricWriteSchemaTargetType,
        data: typing.Sequence[typing.Dict[str, typing.Any]],
        mode: str,
        batch_insert_ok: typing.Optional[bool] = OMIT,
        params_to_match_for_update: typing.Optional[typing.Sequence[str]] = OMIT,
        defaults: typing.Optional[typing.Dict[str, typing.Optional[str]]] = OMIT,
        job_execution_id: typing.Optional[str] = OMIT,
        job_name: typing.Optional[str] = OMIT,
        collect_output: typing.Optional[bool] = OMIT,
        dry_run: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.List[typing.Dict[str, typing.Any]]]:
        """
        Write records to a table.

        Inserts or updates records in the specified target table. Supports batch
        inserts, upserts with match columns, default value functions (DATETIME_NOW,
        UUID4), and optional dry-run validation. A job execution is created
        automatically if one is not provided.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        target_name : str
            The name of the table to write to.

        target_type : LabricWriteSchemaTargetType
            The type of target. Currently 'table' or 'core-table'.

        data : typing.Sequence[typing.Dict[str, typing.Any]]
            List of record dicts to write.

        mode : str
            Write mode (e.g. 'create', 'create-or-update').

        batch_insert_ok : typing.Optional[bool]
            If True, allow batch insert of multiple records.

        params_to_match_for_update : typing.Optional[typing.Sequence[str]]
            Column names to match on when updating existing records.

        defaults : typing.Optional[typing.Dict[str, typing.Optional[str]]]
            Map of field names to default function names (e.g. 'DATETIME_NOW', 'UUID4').

        job_execution_id : typing.Optional[str]
            Existing job execution ID to associate with this write. If omitted, a new one is created.

        job_name : typing.Optional[str]
            Name for the auto-created job. Defaults to 'Off-Platform Manual Job'.

        collect_output : typing.Optional[bool]
            If True, return the written records in the response.

        dry_run : typing.Optional[bool]
            If True, resolve references, check table and column validity, and return the execution plan without committing changes.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.List[typing.Dict[str, typing.Any]]]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/tools/write",
            method="POST",
            json={
                "target_name": target_name,
                "target_type": target_type,
                "data": data,
                "batch_insert_ok": batch_insert_ok,
                "params_to_match_for_update": params_to_match_for_update,
                "defaults": defaults,
                "mode": mode,
                "job_execution_id": job_execution_id,
                "job_name": job_name,
                "collect_output": collect_output,
                "dry_run": dry_run,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[typing.Dict[str, typing.Any]],
                    parse_obj_as(
                        type_=typing.List[typing.Dict[str, typing.Any]],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorSchema,
                        parse_obj_as(
                            type_=ValidationErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def read(
        self,
        *,
        target_name: str,
        target_type: LabricReadSchemaTargetType,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        mode: typing.Optional[LabricReadSchemaMode] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.List[typing.Dict[str, typing.Any]]]:
        """
        Read records from a table.

        Returns records from the specified table matching the given filters.
        Use 'single' mode to retrieve exactly one record, or 'multiple' mode
        to retrieve all matching records.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        target_name : str
            The name of the table to read from.

        target_type : LabricReadSchemaTargetType
            The type of target. Either 'table' or 'core-table'.

        filters : typing.Optional[typing.Dict[str, typing.Any]]
            Key-value filters to apply to the query. Omit to match all records.

        mode : typing.Optional[LabricReadSchemaMode]
            'single' returns exactly one record and throws an error if more than one matching record exists, 'multiple' returns all matches.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.List[typing.Dict[str, typing.Any]]]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/tools/read",
            method="POST",
            json={
                "target_name": target_name,
                "target_type": target_type,
                "filters": filters,
                "mode": mode,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[typing.Dict[str, typing.Any]],
                    parse_obj_as(
                        type_=typing.List[typing.Dict[str, typing.Any]],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorSchema,
                        parse_obj_as(
                            type_=ValidationErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def execute_sql(
        self,
        *,
        query: str,
        params: typing.Optional[typing.Sequence[typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[QueryResult]:
        """
        Execute a read-only SQL query.

        Runs the query against the organization's read replica, so it cannot
        mutate data. Only SELECT statements are accepted. Supports positional
        parameters: write %s placeholders in the query and pass the values in
        order in the params list. Named :param placeholders belong to saved
        dataset queries and are not accepted here. Use the schema tool to discover tables
        first, and reference each column by its sql_column_name — foreign keys
        carry an _id suffix in SQL (e.g. a 'sample' reference is the 'sample_id'
        column).

        Requires an API key with the `read` scope.

        Parameters
        ----------
        query : str

        params : typing.Optional[typing.Sequence[typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[QueryResult]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/tools/query",
            method="POST",
            json={
                "query": query,
                "params": params,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    QueryResult,
                    parse_obj_as(
                        type_=QueryResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorSchema,
                        parse_obj_as(
                            type_=ValidationErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_schema(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.List[QueryableTableSchema]]:
        """
        Describe the organization's data schema.

        Returns every table the agent can target, including its semantic category
        (e.g. raw vs. curated), description, and full column definitions with types,
        nullability, uniqueness, and foreign-key targets. Each column carries two
        names: 'name' is what the read and write tools accept, and 'sql_column_name'
        is the physical column for SQL queries (foreign keys carry an _id suffix).
        The org's own tables are followed by the platform tables (core_experiment,
        core_instrument, and similar) that SQL queries can join against; those have
        no id or semantic category. This is the map a parser writes into: use it to
        plan which tables to populate and how rows link.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.List[QueryableTableSchema]]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/tools/schema",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[QueryableTableSchema],
                    parse_obj_as(
                        type_=typing.List[QueryableTableSchema],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorSchema,
                        parse_obj_as(
                            type_=ValidationErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def batch_write(
        self,
        *,
        tables: typing.Dict[str, typing.Sequence[typing.Dict[str, typing.Any]]],
        options: typing.Optional[BatchWriteOptions] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[BatchWriteResponse]:
        """
        Write records to multiple tables in a single transaction.

        Supports:
        - Batch references: Use "_ref" to label records, "@refname" to reference them
        - Natural keys: Use human-readable values for foreign keys (e.g., recipe name)
        - Automatic FK ordering: Tables are inserted in dependency order
        - Upsert mode: Update existing records based on match columns
        - Dry run: Validate without committing changes

        Committed writes are recorded against a job execution (created automatically
        if not supplied) and the job_execution_id is returned, so the write can be
        reverted as a unit.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        tables : typing.Dict[str, typing.Sequence[typing.Dict[str, typing.Any]]]
            Map of table_name to list of records to insert.

        options : typing.Optional[BatchWriteOptions]
            Optional write options (mode, match_on, dry_run, return_records).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[BatchWriteResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/tools/batch-write",
            method="POST",
            json={
                "tables": tables,
                "options": convert_and_respect_annotation_metadata(
                    object_=options, annotation=typing.Optional[BatchWriteOptions], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BatchWriteResponse,
                    parse_obj_as(
                        type_=BatchWriteResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorSchema,
                        parse_obj_as(
                            type_=ValidationErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawToolsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def write(
        self,
        *,
        target_name: str,
        target_type: LabricWriteSchemaTargetType,
        data: typing.Sequence[typing.Dict[str, typing.Any]],
        mode: str,
        batch_insert_ok: typing.Optional[bool] = OMIT,
        params_to_match_for_update: typing.Optional[typing.Sequence[str]] = OMIT,
        defaults: typing.Optional[typing.Dict[str, typing.Optional[str]]] = OMIT,
        job_execution_id: typing.Optional[str] = OMIT,
        job_name: typing.Optional[str] = OMIT,
        collect_output: typing.Optional[bool] = OMIT,
        dry_run: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.List[typing.Dict[str, typing.Any]]]:
        """
        Write records to a table.

        Inserts or updates records in the specified target table. Supports batch
        inserts, upserts with match columns, default value functions (DATETIME_NOW,
        UUID4), and optional dry-run validation. A job execution is created
        automatically if one is not provided.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        target_name : str
            The name of the table to write to.

        target_type : LabricWriteSchemaTargetType
            The type of target. Currently 'table' or 'core-table'.

        data : typing.Sequence[typing.Dict[str, typing.Any]]
            List of record dicts to write.

        mode : str
            Write mode (e.g. 'create', 'create-or-update').

        batch_insert_ok : typing.Optional[bool]
            If True, allow batch insert of multiple records.

        params_to_match_for_update : typing.Optional[typing.Sequence[str]]
            Column names to match on when updating existing records.

        defaults : typing.Optional[typing.Dict[str, typing.Optional[str]]]
            Map of field names to default function names (e.g. 'DATETIME_NOW', 'UUID4').

        job_execution_id : typing.Optional[str]
            Existing job execution ID to associate with this write. If omitted, a new one is created.

        job_name : typing.Optional[str]
            Name for the auto-created job. Defaults to 'Off-Platform Manual Job'.

        collect_output : typing.Optional[bool]
            If True, return the written records in the response.

        dry_run : typing.Optional[bool]
            If True, resolve references, check table and column validity, and return the execution plan without committing changes.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.List[typing.Dict[str, typing.Any]]]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/tools/write",
            method="POST",
            json={
                "target_name": target_name,
                "target_type": target_type,
                "data": data,
                "batch_insert_ok": batch_insert_ok,
                "params_to_match_for_update": params_to_match_for_update,
                "defaults": defaults,
                "mode": mode,
                "job_execution_id": job_execution_id,
                "job_name": job_name,
                "collect_output": collect_output,
                "dry_run": dry_run,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[typing.Dict[str, typing.Any]],
                    parse_obj_as(
                        type_=typing.List[typing.Dict[str, typing.Any]],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorSchema,
                        parse_obj_as(
                            type_=ValidationErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def read(
        self,
        *,
        target_name: str,
        target_type: LabricReadSchemaTargetType,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        mode: typing.Optional[LabricReadSchemaMode] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.List[typing.Dict[str, typing.Any]]]:
        """
        Read records from a table.

        Returns records from the specified table matching the given filters.
        Use 'single' mode to retrieve exactly one record, or 'multiple' mode
        to retrieve all matching records.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        target_name : str
            The name of the table to read from.

        target_type : LabricReadSchemaTargetType
            The type of target. Either 'table' or 'core-table'.

        filters : typing.Optional[typing.Dict[str, typing.Any]]
            Key-value filters to apply to the query. Omit to match all records.

        mode : typing.Optional[LabricReadSchemaMode]
            'single' returns exactly one record and throws an error if more than one matching record exists, 'multiple' returns all matches.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.List[typing.Dict[str, typing.Any]]]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/tools/read",
            method="POST",
            json={
                "target_name": target_name,
                "target_type": target_type,
                "filters": filters,
                "mode": mode,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[typing.Dict[str, typing.Any]],
                    parse_obj_as(
                        type_=typing.List[typing.Dict[str, typing.Any]],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorSchema,
                        parse_obj_as(
                            type_=ValidationErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def execute_sql(
        self,
        *,
        query: str,
        params: typing.Optional[typing.Sequence[typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[QueryResult]:
        """
        Execute a read-only SQL query.

        Runs the query against the organization's read replica, so it cannot
        mutate data. Only SELECT statements are accepted. Supports positional
        parameters: write %s placeholders in the query and pass the values in
        order in the params list. Named :param placeholders belong to saved
        dataset queries and are not accepted here. Use the schema tool to discover tables
        first, and reference each column by its sql_column_name — foreign keys
        carry an _id suffix in SQL (e.g. a 'sample' reference is the 'sample_id'
        column).

        Requires an API key with the `read` scope.

        Parameters
        ----------
        query : str

        params : typing.Optional[typing.Sequence[typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[QueryResult]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/tools/query",
            method="POST",
            json={
                "query": query,
                "params": params,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    QueryResult,
                    parse_obj_as(
                        type_=QueryResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorSchema,
                        parse_obj_as(
                            type_=ValidationErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_schema(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.List[QueryableTableSchema]]:
        """
        Describe the organization's data schema.

        Returns every table the agent can target, including its semantic category
        (e.g. raw vs. curated), description, and full column definitions with types,
        nullability, uniqueness, and foreign-key targets. Each column carries two
        names: 'name' is what the read and write tools accept, and 'sql_column_name'
        is the physical column for SQL queries (foreign keys carry an _id suffix).
        The org's own tables are followed by the platform tables (core_experiment,
        core_instrument, and similar) that SQL queries can join against; those have
        no id or semantic category. This is the map a parser writes into: use it to
        plan which tables to populate and how rows link.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.List[QueryableTableSchema]]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/tools/schema",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[QueryableTableSchema],
                    parse_obj_as(
                        type_=typing.List[QueryableTableSchema],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorSchema,
                        parse_obj_as(
                            type_=ValidationErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def batch_write(
        self,
        *,
        tables: typing.Dict[str, typing.Sequence[typing.Dict[str, typing.Any]]],
        options: typing.Optional[BatchWriteOptions] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[BatchWriteResponse]:
        """
        Write records to multiple tables in a single transaction.

        Supports:
        - Batch references: Use "_ref" to label records, "@refname" to reference them
        - Natural keys: Use human-readable values for foreign keys (e.g., recipe name)
        - Automatic FK ordering: Tables are inserted in dependency order
        - Upsert mode: Update existing records based on match columns
        - Dry run: Validate without committing changes

        Committed writes are recorded against a job execution (created automatically
        if not supplied) and the job_execution_id is returned, so the write can be
        reverted as a unit.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        tables : typing.Dict[str, typing.Sequence[typing.Dict[str, typing.Any]]]
            Map of table_name to list of records to insert.

        options : typing.Optional[BatchWriteOptions]
            Optional write options (mode, match_on, dry_run, return_records).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[BatchWriteResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/tools/batch-write",
            method="POST",
            json={
                "tables": tables,
                "options": convert_and_respect_annotation_metadata(
                    object_=options, annotation=typing.Optional[BatchWriteOptions], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BatchWriteResponse,
                    parse_obj_as(
                        type_=BatchWriteResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorSchema,
                        parse_obj_as(
                            type_=ValidationErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
