# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        BatchWriteOptions,
        BatchWriteOptionsMode,
        BatchWriteResponse,
        ColumnInfoSchema,
        ErrorSchema,
        LabricUploadFileSchema,
        QueryResult,
        RevertResultSchema,
        TableSchemaInfoSchema,
        TableSummary,
        ToolsFileContentSchema,
        ToolsFileInfoSchema,
        WritePlan,
    )
    from .errors import (
        BadGatewayError,
        BadRequestError,
        ConflictError,
        ForbiddenError,
        GatewayTimeoutError,
        GoneError,
        ImATeapotError,
        InternalServerError,
        LengthRequiredError,
        MethodNotAllowedError,
        NotAcceptableError,
        NotFoundError,
        NotImplementedError,
        PaymentRequiredError,
        PreconditionFailedError,
        ProxyAuthenticationRequiredError,
        RangeNotSatisfiableError,
        RequestTimeoutError,
        ServiceUnavailableError,
        TooEarlyError,
        TooManyRequestsError,
        UnauthorizedError,
        UnavailableForLegalReasonsError,
    )
    from . import tools
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .client import AsyncLabricApi, LabricApi
    from .environment import LabricApiEnvironment
    from .tools import LabricReadSchemaMode, LabricReadSchemaTargetType, LabricWriteSchemaTargetType
_dynamic_imports: typing.Dict[str, str] = {
    "AsyncLabricApi": ".client",
    "BadGatewayError": ".errors",
    "BadRequestError": ".errors",
    "BatchWriteOptions": ".types",
    "BatchWriteOptionsMode": ".types",
    "BatchWriteResponse": ".types",
    "ColumnInfoSchema": ".types",
    "ConflictError": ".errors",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "ErrorSchema": ".types",
    "ForbiddenError": ".errors",
    "GatewayTimeoutError": ".errors",
    "GoneError": ".errors",
    "ImATeapotError": ".errors",
    "InternalServerError": ".errors",
    "LabricApi": ".client",
    "LabricApiEnvironment": ".environment",
    "LabricReadSchemaMode": ".tools",
    "LabricReadSchemaTargetType": ".tools",
    "LabricUploadFileSchema": ".types",
    "LabricWriteSchemaTargetType": ".tools",
    "LengthRequiredError": ".errors",
    "MethodNotAllowedError": ".errors",
    "NotAcceptableError": ".errors",
    "NotFoundError": ".errors",
    "NotImplementedError": ".errors",
    "PaymentRequiredError": ".errors",
    "PreconditionFailedError": ".errors",
    "ProxyAuthenticationRequiredError": ".errors",
    "QueryResult": ".types",
    "RangeNotSatisfiableError": ".errors",
    "RequestTimeoutError": ".errors",
    "RevertResultSchema": ".types",
    "ServiceUnavailableError": ".errors",
    "TableSchemaInfoSchema": ".types",
    "TableSummary": ".types",
    "TooEarlyError": ".errors",
    "TooManyRequestsError": ".errors",
    "ToolsFileContentSchema": ".types",
    "ToolsFileInfoSchema": ".types",
    "UnauthorizedError": ".errors",
    "UnavailableForLegalReasonsError": ".errors",
    "WritePlan": ".types",
    "tools": ".tools",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AsyncLabricApi",
    "BadGatewayError",
    "BadRequestError",
    "BatchWriteOptions",
    "BatchWriteOptionsMode",
    "BatchWriteResponse",
    "ColumnInfoSchema",
    "ConflictError",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "ErrorSchema",
    "ForbiddenError",
    "GatewayTimeoutError",
    "GoneError",
    "ImATeapotError",
    "InternalServerError",
    "LabricApi",
    "LabricApiEnvironment",
    "LabricReadSchemaMode",
    "LabricReadSchemaTargetType",
    "LabricUploadFileSchema",
    "LabricWriteSchemaTargetType",
    "LengthRequiredError",
    "MethodNotAllowedError",
    "NotAcceptableError",
    "NotFoundError",
    "NotImplementedError",
    "PaymentRequiredError",
    "PreconditionFailedError",
    "ProxyAuthenticationRequiredError",
    "QueryResult",
    "RangeNotSatisfiableError",
    "RequestTimeoutError",
    "RevertResultSchema",
    "ServiceUnavailableError",
    "TableSchemaInfoSchema",
    "TableSummary",
    "TooEarlyError",
    "TooManyRequestsError",
    "ToolsFileContentSchema",
    "ToolsFileInfoSchema",
    "UnauthorizedError",
    "UnavailableForLegalReasonsError",
    "WritePlan",
    "tools",
]
