# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        AgentRunEvent,
        AgentRunRequest,
        AgentRunResponse,
        AgentRunUsage,
        AgentToolCall,
        BatchWriteOptions,
        BatchWriteOptionsMode,
        BatchWriteResponse,
        ErrorSchema,
        FileContentSchema,
        FileInfoSchema,
        FileUploadSchema,
        MlModelTaskType,
        MlProblemType,
        OffPlatformJobExecutionSchema,
        PredictResponseSchema,
        PredictedAnnotationSchema,
        QualityPreset,
        QueryResult,
        QueryableColumnSchema,
        QueryableTableSchema,
        RevertResultSchema,
        StartJobExecutionSchema,
        TableSummary,
        ToolsMlModelDetailSchema,
        ValidationErrorSchema,
        WritePlan,
    )
    from .errors import (
        BadGatewayError,
        BadRequestError,
        ConflictError,
        ForbiddenError,
        InternalServerError,
        NotFoundError,
        ServiceUnavailableError,
        TooManyRequestsError,
        UnauthorizedError,
        UnprocessableEntityError,
    )
    from . import agent, files, jobs, models, tools
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .client import AsyncLabric, Labric
    from .environment import LabricEnvironment
    from .jobs import UpdateJobExecutionStatusSchemaStatus
    from .tools import LabricReadSchemaMode, LabricReadSchemaTargetType, LabricWriteSchemaTargetType
_dynamic_imports: typing.Dict[str, str] = {
    "AgentRunEvent": ".types",
    "AgentRunRequest": ".types",
    "AgentRunResponse": ".types",
    "AgentRunUsage": ".types",
    "AgentToolCall": ".types",
    "AsyncLabric": ".client",
    "BadGatewayError": ".errors",
    "BadRequestError": ".errors",
    "BatchWriteOptions": ".types",
    "BatchWriteOptionsMode": ".types",
    "BatchWriteResponse": ".types",
    "ConflictError": ".errors",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "ErrorSchema": ".types",
    "FileContentSchema": ".types",
    "FileInfoSchema": ".types",
    "FileUploadSchema": ".types",
    "ForbiddenError": ".errors",
    "InternalServerError": ".errors",
    "Labric": ".client",
    "LabricEnvironment": ".environment",
    "LabricReadSchemaMode": ".tools",
    "LabricReadSchemaTargetType": ".tools",
    "LabricWriteSchemaTargetType": ".tools",
    "MlModelTaskType": ".types",
    "MlProblemType": ".types",
    "NotFoundError": ".errors",
    "OffPlatformJobExecutionSchema": ".types",
    "PredictResponseSchema": ".types",
    "PredictedAnnotationSchema": ".types",
    "QualityPreset": ".types",
    "QueryResult": ".types",
    "QueryableColumnSchema": ".types",
    "QueryableTableSchema": ".types",
    "RevertResultSchema": ".types",
    "ServiceUnavailableError": ".errors",
    "StartJobExecutionSchema": ".types",
    "TableSummary": ".types",
    "TooManyRequestsError": ".errors",
    "ToolsMlModelDetailSchema": ".types",
    "UnauthorizedError": ".errors",
    "UnprocessableEntityError": ".errors",
    "UpdateJobExecutionStatusSchemaStatus": ".jobs",
    "ValidationErrorSchema": ".types",
    "WritePlan": ".types",
    "agent": ".agent",
    "files": ".files",
    "jobs": ".jobs",
    "models": ".models",
    "tools": ".tools",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AgentRunEvent",
    "AgentRunRequest",
    "AgentRunResponse",
    "AgentRunUsage",
    "AgentToolCall",
    "AsyncLabric",
    "BadGatewayError",
    "BadRequestError",
    "BatchWriteOptions",
    "BatchWriteOptionsMode",
    "BatchWriteResponse",
    "ConflictError",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "ErrorSchema",
    "FileContentSchema",
    "FileInfoSchema",
    "FileUploadSchema",
    "ForbiddenError",
    "InternalServerError",
    "Labric",
    "LabricEnvironment",
    "LabricReadSchemaMode",
    "LabricReadSchemaTargetType",
    "LabricWriteSchemaTargetType",
    "MlModelTaskType",
    "MlProblemType",
    "NotFoundError",
    "OffPlatformJobExecutionSchema",
    "PredictResponseSchema",
    "PredictedAnnotationSchema",
    "QualityPreset",
    "QueryResult",
    "QueryableColumnSchema",
    "QueryableTableSchema",
    "RevertResultSchema",
    "ServiceUnavailableError",
    "StartJobExecutionSchema",
    "TableSummary",
    "TooManyRequestsError",
    "ToolsMlModelDetailSchema",
    "UnauthorizedError",
    "UnprocessableEntityError",
    "UpdateJobExecutionStatusSchemaStatus",
    "ValidationErrorSchema",
    "WritePlan",
    "agent",
    "files",
    "jobs",
    "models",
    "tools",
]
