# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        BatchWriteOptions,
        BatchWriteOptionsMode,
        BatchWriteResponse,
        ColumnInfoSchema,
        ErrorSchema,
        LabricUploadFileSchema,
        PredictResponseSchema,
        QueryResult,
        RevertResultSchema,
        TableSchemaInfoSchema,
        TableSummary,
        ToolsFileContentSchema,
        ToolsFileInfoSchema,
        ToolsMlModelSchema,
        ValidationErrorSchema,
        WritePlan,
    )
    from .errors import (
        BadGatewayError,
        BadRequestError,
        ForbiddenError,
        InternalServerError,
        NotFoundError,
        ServiceUnavailableError,
        UnauthorizedError,
        UnprocessableEntityError,
    )
    from . import tools
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .client import AsyncLabric, Labric
    from .environment import LabricEnvironment
    from .tools import LabricReadSchemaMode, LabricReadSchemaTargetType, LabricWriteSchemaTargetType
_dynamic_imports: typing.Dict[str, str] = {
    "AsyncLabric": ".client",
    "BadGatewayError": ".errors",
    "BadRequestError": ".errors",
    "BatchWriteOptions": ".types",
    "BatchWriteOptionsMode": ".types",
    "BatchWriteResponse": ".types",
    "ColumnInfoSchema": ".types",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "ErrorSchema": ".types",
    "ForbiddenError": ".errors",
    "InternalServerError": ".errors",
    "Labric": ".client",
    "LabricEnvironment": ".environment",
    "LabricReadSchemaMode": ".tools",
    "LabricReadSchemaTargetType": ".tools",
    "LabricUploadFileSchema": ".types",
    "LabricWriteSchemaTargetType": ".tools",
    "NotFoundError": ".errors",
    "PredictResponseSchema": ".types",
    "QueryResult": ".types",
    "RevertResultSchema": ".types",
    "ServiceUnavailableError": ".errors",
    "TableSchemaInfoSchema": ".types",
    "TableSummary": ".types",
    "ToolsFileContentSchema": ".types",
    "ToolsFileInfoSchema": ".types",
    "ToolsMlModelSchema": ".types",
    "UnauthorizedError": ".errors",
    "UnprocessableEntityError": ".errors",
    "ValidationErrorSchema": ".types",
    "WritePlan": ".types",
    "tools": ".tools",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AsyncLabric",
    "BadGatewayError",
    "BadRequestError",
    "BatchWriteOptions",
    "BatchWriteOptionsMode",
    "BatchWriteResponse",
    "ColumnInfoSchema",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "ErrorSchema",
    "ForbiddenError",
    "InternalServerError",
    "Labric",
    "LabricEnvironment",
    "LabricReadSchemaMode",
    "LabricReadSchemaTargetType",
    "LabricUploadFileSchema",
    "LabricWriteSchemaTargetType",
    "NotFoundError",
    "PredictResponseSchema",
    "QueryResult",
    "RevertResultSchema",
    "ServiceUnavailableError",
    "TableSchemaInfoSchema",
    "TableSummary",
    "ToolsFileContentSchema",
    "ToolsFileInfoSchema",
    "ToolsMlModelSchema",
    "UnauthorizedError",
    "UnprocessableEntityError",
    "ValidationErrorSchema",
    "WritePlan",
    "tools",
]
